// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/configprofile"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// ConfigProfileUpdate is the builder for updating ConfigProfile entities.
type ConfigProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigProfileMutation
}

// Where appends a list predicates to the ConfigProfileUpdate builder.
func (_u *ConfigProfileUpdate) Where(ps ...predicate.ConfigProfile) *ConfigProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ConfigProfileUpdate) SetName(v string) *ConfigProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConfigProfileUpdate) SetNillableName(v *string) *ConfigProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEncryptedData sets the "encrypted_data" field.
func (_u *ConfigProfileUpdate) SetEncryptedData(v []byte) *ConfigProfileUpdate {
	_u.mutation.SetEncryptedData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *ConfigProfileUpdate) SetActive(v bool) *ConfigProfileUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ConfigProfileUpdate) SetNillableActive(v *bool) *ConfigProfileUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ConfigProfileUpdate) SetVersion(v int) *ConfigProfileUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ConfigProfileUpdate) SetNillableVersion(v *int) *ConfigProfileUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ConfigProfileUpdate) AddVersion(v int) *ConfigProfileUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigProfileUpdate) SetUpdatedAt(v time.Time) *ConfigProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ConfigProfileMutation object of the builder.
func (_u *ConfigProfileUpdate) Mutation() *ConfigProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigProfileUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := configprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ConfigProfile.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configprofile.Table, configprofile.Columns, sqlgraph.NewFieldSpec(configprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(configprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedData(); ok {
		_spec.SetField(configprofile.FieldEncryptedData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(configprofile.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(configprofile.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(configprofile.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigProfileUpdateOne is the builder for updating a single ConfigProfile entity.
type ConfigProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigProfileMutation
}

// SetName sets the "name" field.
func (_u *ConfigProfileUpdateOne) SetName(v string) *ConfigProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConfigProfileUpdateOne) SetNillableName(v *string) *ConfigProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEncryptedData sets the "encrypted_data" field.
func (_u *ConfigProfileUpdateOne) SetEncryptedData(v []byte) *ConfigProfileUpdateOne {
	_u.mutation.SetEncryptedData(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *ConfigProfileUpdateOne) SetActive(v bool) *ConfigProfileUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ConfigProfileUpdateOne) SetNillableActive(v *bool) *ConfigProfileUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ConfigProfileUpdateOne) SetVersion(v int) *ConfigProfileUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ConfigProfileUpdateOne) SetNillableVersion(v *int) *ConfigProfileUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ConfigProfileUpdateOne) AddVersion(v int) *ConfigProfileUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigProfileUpdateOne) SetUpdatedAt(v time.Time) *ConfigProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ConfigProfileMutation object of the builder.
func (_u *ConfigProfileUpdateOne) Mutation() *ConfigProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConfigProfileUpdate builder.
func (_u *ConfigProfileUpdateOne) Where(ps ...predicate.ConfigProfile) *ConfigProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigProfileUpdateOne) Select(field string, fields ...string) *ConfigProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfigProfile entity.
func (_u *ConfigProfileUpdateOne) Save(ctx context.Context) (*ConfigProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigProfileUpdateOne) SaveX(ctx context.Context) *ConfigProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := configprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ConfigProfile.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigProfileUpdateOne) sqlSave(ctx context.Context) (_node *ConfigProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configprofile.Table, configprofile.Columns, sqlgraph.NewFieldSpec(configprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfigProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configprofile.FieldID)
		for _, f := range fields {
			if !configprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(configprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedData(); ok {
		_spec.SetField(configprofile.FieldEncryptedData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(configprofile.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(configprofile.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(configprofile.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ConfigProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
