// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/configprofile"
)

// ConfigProfileCreate is the builder for creating a ConfigProfile entity.
type ConfigProfileCreate struct {
	config
	mutation *ConfigProfileMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ConfigProfileCreate) SetName(v string) *ConfigProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEncryptedData sets the "encrypted_data" field.
func (_c *ConfigProfileCreate) SetEncryptedData(v []byte) *ConfigProfileCreate {
	_c.mutation.SetEncryptedData(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *ConfigProfileCreate) SetActive(v bool) *ConfigProfileCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *ConfigProfileCreate) SetNillableActive(v *bool) *ConfigProfileCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ConfigProfileCreate) SetVersion(v int) *ConfigProfileCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ConfigProfileCreate) SetNillableVersion(v *int) *ConfigProfileCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConfigProfileCreate) SetCreatedAt(v time.Time) *ConfigProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConfigProfileCreate) SetNillableCreatedAt(v *time.Time) *ConfigProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConfigProfileCreate) SetUpdatedAt(v time.Time) *ConfigProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConfigProfileCreate) SetNillableUpdatedAt(v *time.Time) *ConfigProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ConfigProfileCreate) SetID(v uuid.UUID) *ConfigProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConfigProfileCreate) SetNillableID(v *uuid.UUID) *ConfigProfileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ConfigProfileMutation object of the builder.
func (_c *ConfigProfileCreate) Mutation() *ConfigProfileMutation {
	return _c.mutation
}

// Save creates the ConfigProfile in the database.
func (_c *ConfigProfileCreate) Save(ctx context.Context) (*ConfigProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfigProfileCreate) SaveX(ctx context.Context) *ConfigProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConfigProfileCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := configprofile.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := configprofile.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := configprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := configprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := configprofile.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfigProfileCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ConfigProfile.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := configprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ConfigProfile.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedData(); !ok {
		return &ValidationError{Name: "encrypted_data", err: errors.New(`ent: missing required field "ConfigProfile.encrypted_data"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "ConfigProfile.active"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ConfigProfile.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConfigProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConfigProfile.updated_at"`)}
	}
	return nil
}

func (_c *ConfigProfileCreate) sqlSave(ctx context.Context) (*ConfigProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfigProfileCreate) createSpec() (*ConfigProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ConfigProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(configprofile.Table, sqlgraph.NewFieldSpec(configprofile.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(configprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.EncryptedData(); ok {
		_spec.SetField(configprofile.FieldEncryptedData, field.TypeBytes, value)
		_node.EncryptedData = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(configprofile.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(configprofile.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(configprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(configprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ConfigProfileCreateBulk is the builder for creating many ConfigProfile entities in bulk.
type ConfigProfileCreateBulk struct {
	config
	err      error
	builders []*ConfigProfileCreate
}

// Save creates the ConfigProfile entities in the database.
func (_c *ConfigProfileCreateBulk) Save(ctx context.Context) ([]*ConfigProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConfigProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfigProfileCreateBulk) SaveX(ctx context.Context) []*ConfigProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
