// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/configprofile"
)

// ConfigProfile is the model entity for the ConfigProfile schema.
type ConfigProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Profile identifier (e.g., default, staging, production)
	Name string `json:"name,omitempty"`
	// AES-256-GCM encrypted JSON configuration blob
	EncryptedData []byte `json:"encrypted_data,omitempty"`
	// Whether this profile is the currently active one
	Active bool `json:"active,omitempty"`
	// Schema version for forward compatibility
	Version int `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConfigProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configprofile.FieldEncryptedData:
			values[i] = new([]byte)
		case configprofile.FieldActive:
			values[i] = new(sql.NullBool)
		case configprofile.FieldVersion:
			values[i] = new(sql.NullInt64)
		case configprofile.FieldName:
			values[i] = new(sql.NullString)
		case configprofile.FieldCreatedAt, configprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case configprofile.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConfigProfile fields.
func (_m *ConfigProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configprofile.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case configprofile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case configprofile.FieldEncryptedData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_data", values[i])
			} else if value != nil {
				_m.EncryptedData = *value
			}
		case configprofile.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case configprofile.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case configprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case configprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConfigProfile.
// This includes values selected through modifiers, order, etc.
func (_m *ConfigProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ConfigProfile.
// Note that you need to call ConfigProfile.Unwrap() before calling this method if this ConfigProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConfigProfile) Update() *ConfigProfileUpdateOne {
	return NewConfigProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConfigProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConfigProfile) Unwrap() *ConfigProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConfigProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConfigProfile) String() string {
	var builder strings.Builder
	builder.WriteString("ConfigProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("encrypted_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedData))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConfigProfiles is a parsable slice of ConfigProfile.
type ConfigProfiles []*ConfigProfile
