// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/cronjob"
)

// CronJobCreate is the builder for creating a CronJob entity.
type CronJobCreate struct {
	config
	mutation *CronJobMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CronJobCreate) SetName(v string) *CronJobCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetScheduleType sets the "schedule_type" field.
func (_c *CronJobCreate) SetScheduleType(v cronjob.ScheduleType) *CronJobCreate {
	_c.mutation.SetScheduleType(v)
	return _c
}

// SetSchedule sets the "schedule" field.
func (_c *CronJobCreate) SetSchedule(v string) *CronJobCreate {
	_c.mutation.SetSchedule(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *CronJobCreate) SetPrompt(v string) *CronJobCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetSessionMode sets the "session_mode" field.
func (_c *CronJobCreate) SetSessionMode(v string) *CronJobCreate {
	_c.mutation.SetSessionMode(v)
	return _c
}

// SetNillableSessionMode sets the "session_mode" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableSessionMode(v *string) *CronJobCreate {
	if v != nil {
		_c.SetSessionMode(*v)
	}
	return _c
}

// SetDeliverTo sets the "deliver_to" field.
func (_c *CronJobCreate) SetDeliverTo(v []string) *CronJobCreate {
	_c.mutation.SetDeliverTo(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *CronJobCreate) SetTimezone(v string) *CronJobCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableTimezone(v *string) *CronJobCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CronJobCreate) SetEnabled(v bool) *CronJobCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableEnabled(v *bool) *CronJobCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *CronJobCreate) SetLastRunAt(v time.Time) *CronJobCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableLastRunAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *CronJobCreate) SetNextRunAt(v time.Time) *CronJobCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableNextRunAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CronJobCreate) SetCreatedAt(v time.Time) *CronJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableCreatedAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CronJobCreate) SetUpdatedAt(v time.Time) *CronJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableUpdatedAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CronJobCreate) SetID(v uuid.UUID) *CronJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableID(v *uuid.UUID) *CronJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CronJobMutation object of the builder.
func (_c *CronJobCreate) Mutation() *CronJobMutation {
	return _c.mutation
}

// Save creates the CronJob in the database.
func (_c *CronJobCreate) Save(ctx context.Context) (*CronJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CronJobCreate) SaveX(ctx context.Context) *CronJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CronJobCreate) defaults() {
	if _, ok := _c.mutation.SessionMode(); !ok {
		v := cronjob.DefaultSessionMode
		_c.mutation.SetSessionMode(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := cronjob.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := cronjob.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cronjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cronjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := cronjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CronJobCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CronJob.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduleType(); !ok {
		return &ValidationError{Name: "schedule_type", err: errors.New(`ent: missing required field "CronJob.schedule_type"`)}
	}
	if v, ok := _c.mutation.ScheduleType(); ok {
		if err := cronjob.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Schedule(); !ok {
		return &ValidationError{Name: "schedule", err: errors.New(`ent: missing required field "CronJob.schedule"`)}
	}
	if v, ok := _c.mutation.Schedule(); ok {
		if err := cronjob.ScheduleValidator(v); err != nil {
			return &ValidationError{Name: "schedule", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "CronJob.prompt"`)}
	}
	if v, ok := _c.mutation.Prompt(); ok {
		if err := cronjob.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "CronJob.prompt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionMode(); !ok {
		return &ValidationError{Name: "session_mode", err: errors.New(`ent: missing required field "CronJob.session_mode"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "CronJob.timezone"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CronJob.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CronJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CronJob.updated_at"`)}
	}
	return nil
}

func (_c *CronJobCreate) sqlSave(ctx context.Context) (*CronJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CronJobCreate) createSpec() (*CronJob, *sqlgraph.CreateSpec) {
	var (
		_node = &CronJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cronjob.Table, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ScheduleType(); ok {
		_spec.SetField(cronjob.FieldScheduleType, field.TypeEnum, value)
		_node.ScheduleType = value
	}
	if value, ok := _c.mutation.Schedule(); ok {
		_spec.SetField(cronjob.FieldSchedule, field.TypeString, value)
		_node.Schedule = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(cronjob.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.SessionMode(); ok {
		_spec.SetField(cronjob.FieldSessionMode, field.TypeString, value)
		_node.SessionMode = value
	}
	if value, ok := _c.mutation.DeliverTo(); ok {
		_spec.SetField(cronjob.FieldDeliverTo, field.TypeJSON, value)
		_node.DeliverTo = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(cronjob.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(cronjob.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = &value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(cronjob.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cronjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cronjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CronJobCreateBulk is the builder for creating many CronJob entities in bulk.
type CronJobCreateBulk struct {
	config
	err      error
	builders []*CronJobCreate
}

// Save creates the CronJob entities in the database.
func (_c *CronJobCreateBulk) Save(ctx context.Context) ([]*CronJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CronJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CronJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CronJobCreateBulk) SaveX(ctx context.Context) []*CronJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
