// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/cronjob"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// CronJobUpdate is the builder for updating CronJob entities.
type CronJobUpdate struct {
	config
	hooks    []Hook
	mutation *CronJobMutation
}

// Where appends a list predicates to the CronJobUpdate builder.
func (_u *CronJobUpdate) Where(ps ...predicate.CronJob) *CronJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CronJobUpdate) SetName(v string) *CronJobUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableName(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *CronJobUpdate) SetScheduleType(v cronjob.ScheduleType) *CronJobUpdate {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableScheduleType(v *cronjob.ScheduleType) *CronJobUpdate {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetSchedule sets the "schedule" field.
func (_u *CronJobUpdate) SetSchedule(v string) *CronJobUpdate {
	_u.mutation.SetSchedule(v)
	return _u
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableSchedule(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetSchedule(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *CronJobUpdate) SetPrompt(v string) *CronJobUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillablePrompt(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSessionMode sets the "session_mode" field.
func (_u *CronJobUpdate) SetSessionMode(v string) *CronJobUpdate {
	_u.mutation.SetSessionMode(v)
	return _u
}

// SetNillableSessionMode sets the "session_mode" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableSessionMode(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetSessionMode(*v)
	}
	return _u
}

// SetDeliverTo sets the "deliver_to" field.
func (_u *CronJobUpdate) SetDeliverTo(v []string) *CronJobUpdate {
	_u.mutation.SetDeliverTo(v)
	return _u
}

// AppendDeliverTo appends value to the "deliver_to" field.
func (_u *CronJobUpdate) AppendDeliverTo(v []string) *CronJobUpdate {
	_u.mutation.AppendDeliverTo(v)
	return _u
}

// ClearDeliverTo clears the value of the "deliver_to" field.
func (_u *CronJobUpdate) ClearDeliverTo() *CronJobUpdate {
	_u.mutation.ClearDeliverTo()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *CronJobUpdate) SetTimezone(v string) *CronJobUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableTimezone(v *string) *CronJobUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CronJobUpdate) SetEnabled(v bool) *CronJobUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableEnabled(v *bool) *CronJobUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *CronJobUpdate) SetLastRunAt(v time.Time) *CronJobUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableLastRunAt(v *time.Time) *CronJobUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *CronJobUpdate) ClearLastRunAt() *CronJobUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *CronJobUpdate) SetNextRunAt(v time.Time) *CronJobUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *CronJobUpdate) SetNillableNextRunAt(v *time.Time) *CronJobUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *CronJobUpdate) ClearNextRunAt() *CronJobUpdate {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CronJobUpdate) SetUpdatedAt(v time.Time) *CronJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CronJobMutation object of the builder.
func (_u *CronJobUpdate) Mutation() *CronJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CronJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CronJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CronJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CronJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CronJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cronjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CronJobUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := cronjob.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Schedule(); ok {
		if err := cronjob.ScheduleValidator(v); err != nil {
			return &ValidationError{Name: "schedule", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := cronjob.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "CronJob.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *CronJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(cronjob.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Schedule(); ok {
		_spec.SetField(cronjob.FieldSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(cronjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionMode(); ok {
		_spec.SetField(cronjob.FieldSessionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliverTo(); ok {
		_spec.SetField(cronjob.FieldDeliverTo, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeliverTo(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cronjob.FieldDeliverTo, value)
		})
	}
	if _u.mutation.DeliverToCleared() {
		_spec.ClearField(cronjob.FieldDeliverTo, field.TypeJSON)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(cronjob.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(cronjob.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(cronjob.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(cronjob.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(cronjob.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cronjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CronJobUpdateOne is the builder for updating a single CronJob entity.
type CronJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CronJobMutation
}

// SetName sets the "name" field.
func (_u *CronJobUpdateOne) SetName(v string) *CronJobUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableName(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *CronJobUpdateOne) SetScheduleType(v cronjob.ScheduleType) *CronJobUpdateOne {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableScheduleType(v *cronjob.ScheduleType) *CronJobUpdateOne {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetSchedule sets the "schedule" field.
func (_u *CronJobUpdateOne) SetSchedule(v string) *CronJobUpdateOne {
	_u.mutation.SetSchedule(v)
	return _u
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableSchedule(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetSchedule(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *CronJobUpdateOne) SetPrompt(v string) *CronJobUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillablePrompt(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSessionMode sets the "session_mode" field.
func (_u *CronJobUpdateOne) SetSessionMode(v string) *CronJobUpdateOne {
	_u.mutation.SetSessionMode(v)
	return _u
}

// SetNillableSessionMode sets the "session_mode" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableSessionMode(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetSessionMode(*v)
	}
	return _u
}

// SetDeliverTo sets the "deliver_to" field.
func (_u *CronJobUpdateOne) SetDeliverTo(v []string) *CronJobUpdateOne {
	_u.mutation.SetDeliverTo(v)
	return _u
}

// AppendDeliverTo appends value to the "deliver_to" field.
func (_u *CronJobUpdateOne) AppendDeliverTo(v []string) *CronJobUpdateOne {
	_u.mutation.AppendDeliverTo(v)
	return _u
}

// ClearDeliverTo clears the value of the "deliver_to" field.
func (_u *CronJobUpdateOne) ClearDeliverTo() *CronJobUpdateOne {
	_u.mutation.ClearDeliverTo()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *CronJobUpdateOne) SetTimezone(v string) *CronJobUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableTimezone(v *string) *CronJobUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CronJobUpdateOne) SetEnabled(v bool) *CronJobUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableEnabled(v *bool) *CronJobUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *CronJobUpdateOne) SetLastRunAt(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableLastRunAt(v *time.Time) *CronJobUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *CronJobUpdateOne) ClearLastRunAt() *CronJobUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *CronJobUpdateOne) SetNextRunAt(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *CronJobUpdateOne) SetNillableNextRunAt(v *time.Time) *CronJobUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *CronJobUpdateOne) ClearNextRunAt() *CronJobUpdateOne {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CronJobUpdateOne) SetUpdatedAt(v time.Time) *CronJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CronJobMutation object of the builder.
func (_u *CronJobUpdateOne) Mutation() *CronJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the CronJobUpdate builder.
func (_u *CronJobUpdateOne) Where(ps ...predicate.CronJob) *CronJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CronJobUpdateOne) Select(field string, fields ...string) *CronJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CronJob entity.
func (_u *CronJobUpdateOne) Save(ctx context.Context) (*CronJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CronJobUpdateOne) SaveX(ctx context.Context) *CronJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CronJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CronJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CronJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cronjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CronJobUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := cronjob.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Schedule(); ok {
		if err := cronjob.ScheduleValidator(v); err != nil {
			return &ValidationError{Name: "schedule", err: fmt.Errorf(`ent: validator failed for field "CronJob.schedule": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := cronjob.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "CronJob.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *CronJobUpdateOne) sqlSave(ctx context.Context) (_node *CronJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cronjob.Table, cronjob.Columns, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CronJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cronjob.FieldID)
		for _, f := range fields {
			if !cronjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cronjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(cronjob.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Schedule(); ok {
		_spec.SetField(cronjob.FieldSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(cronjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionMode(); ok {
		_spec.SetField(cronjob.FieldSessionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliverTo(); ok {
		_spec.SetField(cronjob.FieldDeliverTo, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeliverTo(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cronjob.FieldDeliverTo, value)
		})
	}
	if _u.mutation.DeliverToCleared() {
		_spec.ClearField(cronjob.FieldDeliverTo, field.TypeJSON)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(cronjob.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(cronjob.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(cronjob.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(cronjob.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(cronjob.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cronjob.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CronJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cronjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
