// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/inquiry"
)

// Inquiry is the model entity for the Inquiry schema.
type Inquiry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionKey holds the value of the "session_key" field.
	SessionKey string `json:"session_key,omitempty"`
	// Topic holds the value of the "topic" field.
	Topic string `json:"topic,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// Context holds the value of the "context" field.
	Context *string `json:"context,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority inquiry.Priority `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status inquiry.Status `json:"status,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer *string `json:"answer,omitempty"`
	// KnowledgeKey holds the value of the "knowledge_key" field.
	KnowledgeKey *string `json:"knowledge_key,omitempty"`
	// SourceObservationID holds the value of the "source_observation_id" field.
	SourceObservationID *string `json:"source_observation_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt   *time.Time `json:"resolved_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Inquiry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inquiry.FieldSessionKey, inquiry.FieldTopic, inquiry.FieldQuestion, inquiry.FieldContext, inquiry.FieldPriority, inquiry.FieldStatus, inquiry.FieldAnswer, inquiry.FieldKnowledgeKey, inquiry.FieldSourceObservationID:
			values[i] = new(sql.NullString)
		case inquiry.FieldCreatedAt, inquiry.FieldResolvedAt:
			values[i] = new(sql.NullTime)
		case inquiry.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Inquiry fields.
func (_m *Inquiry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inquiry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case inquiry.FieldSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_key", values[i])
			} else if value.Valid {
				_m.SessionKey = value.String
			}
		case inquiry.FieldTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic", values[i])
			} else if value.Valid {
				_m.Topic = value.String
			}
		case inquiry.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case inquiry.FieldContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value.Valid {
				_m.Context = new(string)
				*_m.Context = value.String
			}
		case inquiry.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = inquiry.Priority(value.String)
			}
		case inquiry.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = inquiry.Status(value.String)
			}
		case inquiry.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = new(string)
				*_m.Answer = value.String
			}
		case inquiry.FieldKnowledgeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field knowledge_key", values[i])
			} else if value.Valid {
				_m.KnowledgeKey = new(string)
				*_m.KnowledgeKey = value.String
			}
		case inquiry.FieldSourceObservationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_observation_id", values[i])
			} else if value.Valid {
				_m.SourceObservationID = new(string)
				*_m.SourceObservationID = value.String
			}
		case inquiry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case inquiry.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Inquiry.
// This includes values selected through modifiers, order, etc.
func (_m *Inquiry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Inquiry.
// Note that you need to call Inquiry.Unwrap() before calling this method if this Inquiry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Inquiry) Update() *InquiryUpdateOne {
	return NewInquiryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Inquiry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Inquiry) Unwrap() *Inquiry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Inquiry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Inquiry) String() string {
	var builder strings.Builder
	builder.WriteString("Inquiry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_key=")
	builder.WriteString(_m.SessionKey)
	builder.WriteString(", ")
	builder.WriteString("topic=")
	builder.WriteString(_m.Topic)
	builder.WriteString(", ")
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	if v := _m.Context; v != nil {
		builder.WriteString("context=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.Answer; v != nil {
		builder.WriteString("answer=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.KnowledgeKey; v != nil {
		builder.WriteString("knowledge_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceObservationID; v != nil {
		builder.WriteString("source_observation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Inquiries is a parsable slice of Inquiry.
type Inquiries []*Inquiry
