// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/inquiry"
)

// InquiryCreate is the builder for creating a Inquiry entity.
type InquiryCreate struct {
	config
	mutation *InquiryMutation
	hooks    []Hook
}

// SetSessionKey sets the "session_key" field.
func (_c *InquiryCreate) SetSessionKey(v string) *InquiryCreate {
	_c.mutation.SetSessionKey(v)
	return _c
}

// SetTopic sets the "topic" field.
func (_c *InquiryCreate) SetTopic(v string) *InquiryCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetQuestion sets the "question" field.
func (_c *InquiryCreate) SetQuestion(v string) *InquiryCreate {
	_c.mutation.SetQuestion(v)
	return _c
}

// SetContext sets the "context" field.
func (_c *InquiryCreate) SetContext(v string) *InquiryCreate {
	_c.mutation.SetContext(v)
	return _c
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableContext(v *string) *InquiryCreate {
	if v != nil {
		_c.SetContext(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *InquiryCreate) SetPriority(v inquiry.Priority) *InquiryCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *InquiryCreate) SetNillablePriority(v *inquiry.Priority) *InquiryCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InquiryCreate) SetStatus(v inquiry.Status) *InquiryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableStatus(v *inquiry.Status) *InquiryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAnswer sets the "answer" field.
func (_c *InquiryCreate) SetAnswer(v string) *InquiryCreate {
	_c.mutation.SetAnswer(v)
	return _c
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableAnswer(v *string) *InquiryCreate {
	if v != nil {
		_c.SetAnswer(*v)
	}
	return _c
}

// SetKnowledgeKey sets the "knowledge_key" field.
func (_c *InquiryCreate) SetKnowledgeKey(v string) *InquiryCreate {
	_c.mutation.SetKnowledgeKey(v)
	return _c
}

// SetNillableKnowledgeKey sets the "knowledge_key" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableKnowledgeKey(v *string) *InquiryCreate {
	if v != nil {
		_c.SetKnowledgeKey(*v)
	}
	return _c
}

// SetSourceObservationID sets the "source_observation_id" field.
func (_c *InquiryCreate) SetSourceObservationID(v string) *InquiryCreate {
	_c.mutation.SetSourceObservationID(v)
	return _c
}

// SetNillableSourceObservationID sets the "source_observation_id" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableSourceObservationID(v *string) *InquiryCreate {
	if v != nil {
		_c.SetSourceObservationID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InquiryCreate) SetCreatedAt(v time.Time) *InquiryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableCreatedAt(v *time.Time) *InquiryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *InquiryCreate) SetResolvedAt(v time.Time) *InquiryCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableResolvedAt(v *time.Time) *InquiryCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InquiryCreate) SetID(v uuid.UUID) *InquiryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InquiryCreate) SetNillableID(v *uuid.UUID) *InquiryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InquiryMutation object of the builder.
func (_c *InquiryCreate) Mutation() *InquiryMutation {
	return _c.mutation
}

// Save creates the Inquiry in the database.
func (_c *InquiryCreate) Save(ctx context.Context) (*Inquiry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InquiryCreate) SaveX(ctx context.Context) *Inquiry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InquiryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InquiryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InquiryCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := inquiry.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := inquiry.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inquiry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := inquiry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InquiryCreate) check() error {
	if _, ok := _c.mutation.SessionKey(); !ok {
		return &ValidationError{Name: "session_key", err: errors.New(`ent: missing required field "Inquiry.session_key"`)}
	}
	if v, ok := _c.mutation.SessionKey(); ok {
		if err := inquiry.SessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "session_key", err: fmt.Errorf(`ent: validator failed for field "Inquiry.session_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "Inquiry.topic"`)}
	}
	if v, ok := _c.mutation.Topic(); ok {
		if err := inquiry.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Inquiry.topic": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "Inquiry.question"`)}
	}
	if v, ok := _c.mutation.Question(); ok {
		if err := inquiry.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Inquiry.question": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Inquiry.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := inquiry.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Inquiry.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Inquiry.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := inquiry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inquiry.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Inquiry.created_at"`)}
	}
	return nil
}

func (_c *InquiryCreate) sqlSave(ctx context.Context) (*Inquiry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InquiryCreate) createSpec() (*Inquiry, *sqlgraph.CreateSpec) {
	var (
		_node = &Inquiry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inquiry.Table, sqlgraph.NewFieldSpec(inquiry.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionKey(); ok {
		_spec.SetField(inquiry.FieldSessionKey, field.TypeString, value)
		_node.SessionKey = value
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(inquiry.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.Question(); ok {
		_spec.SetField(inquiry.FieldQuestion, field.TypeString, value)
		_node.Question = value
	}
	if value, ok := _c.mutation.Context(); ok {
		_spec.SetField(inquiry.FieldContext, field.TypeString, value)
		_node.Context = &value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(inquiry.FieldPriority, field.TypeEnum, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(inquiry.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Answer(); ok {
		_spec.SetField(inquiry.FieldAnswer, field.TypeString, value)
		_node.Answer = &value
	}
	if value, ok := _c.mutation.KnowledgeKey(); ok {
		_spec.SetField(inquiry.FieldKnowledgeKey, field.TypeString, value)
		_node.KnowledgeKey = &value
	}
	if value, ok := _c.mutation.SourceObservationID(); ok {
		_spec.SetField(inquiry.FieldSourceObservationID, field.TypeString, value)
		_node.SourceObservationID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inquiry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(inquiry.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	return _node, _spec
}

// InquiryCreateBulk is the builder for creating many Inquiry entities in bulk.
type InquiryCreateBulk struct {
	config
	err      error
	builders []*InquiryCreate
}

// Save creates the Inquiry entities in the database.
func (_c *InquiryCreateBulk) Save(ctx context.Context) ([]*Inquiry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inquiry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InquiryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InquiryCreateBulk) SaveX(ctx context.Context) []*Inquiry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InquiryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InquiryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
