// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/knowledge"
)

// KnowledgeCreate is the builder for creating a Knowledge entity.
type KnowledgeCreate struct {
	config
	mutation *KnowledgeMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *KnowledgeCreate) SetKey(v string) *KnowledgeCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *KnowledgeCreate) SetCategory(v knowledge.Category) *KnowledgeCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *KnowledgeCreate) SetContent(v string) *KnowledgeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *KnowledgeCreate) SetTags(v []string) *KnowledgeCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *KnowledgeCreate) SetSource(v string) *KnowledgeCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableSource(v *string) *KnowledgeCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetUseCount sets the "use_count" field.
func (_c *KnowledgeCreate) SetUseCount(v int) *KnowledgeCreate {
	_c.mutation.SetUseCount(v)
	return _c
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableUseCount(v *int) *KnowledgeCreate {
	if v != nil {
		_c.SetUseCount(*v)
	}
	return _c
}

// SetRelevanceScore sets the "relevance_score" field.
func (_c *KnowledgeCreate) SetRelevanceScore(v float64) *KnowledgeCreate {
	_c.mutation.SetRelevanceScore(v)
	return _c
}

// SetNillableRelevanceScore sets the "relevance_score" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableRelevanceScore(v *float64) *KnowledgeCreate {
	if v != nil {
		_c.SetRelevanceScore(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KnowledgeCreate) SetCreatedAt(v time.Time) *KnowledgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableCreatedAt(v *time.Time) *KnowledgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KnowledgeCreate) SetUpdatedAt(v time.Time) *KnowledgeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableUpdatedAt(v *time.Time) *KnowledgeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KnowledgeCreate) SetID(v uuid.UUID) *KnowledgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KnowledgeCreate) SetNillableID(v *uuid.UUID) *KnowledgeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the KnowledgeMutation object of the builder.
func (_c *KnowledgeCreate) Mutation() *KnowledgeMutation {
	return _c.mutation
}

// Save creates the Knowledge in the database.
func (_c *KnowledgeCreate) Save(ctx context.Context) (*Knowledge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeCreate) SaveX(ctx context.Context) *Knowledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeCreate) defaults() {
	if _, ok := _c.mutation.UseCount(); !ok {
		v := knowledge.DefaultUseCount
		_c.mutation.SetUseCount(v)
	}
	if _, ok := _c.mutation.RelevanceScore(); !ok {
		v := knowledge.DefaultRelevanceScore
		_c.mutation.SetRelevanceScore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := knowledge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := knowledge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := knowledge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Knowledge.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := knowledge.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Knowledge.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Knowledge.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := knowledge.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Knowledge.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Knowledge.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := knowledge.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Knowledge.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		return &ValidationError{Name: "use_count", err: errors.New(`ent: missing required field "Knowledge.use_count"`)}
	}
	if _, ok := _c.mutation.RelevanceScore(); !ok {
		return &ValidationError{Name: "relevance_score", err: errors.New(`ent: missing required field "Knowledge.relevance_score"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Knowledge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Knowledge.updated_at"`)}
	}
	return nil
}

func (_c *KnowledgeCreate) sqlSave(ctx context.Context) (*Knowledge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeCreate) createSpec() (*Knowledge, *sqlgraph.CreateSpec) {
	var (
		_node = &Knowledge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledge.Table, sqlgraph.NewFieldSpec(knowledge.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(knowledge.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(knowledge.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(knowledge.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(knowledge.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(knowledge.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.UseCount(); ok {
		_spec.SetField(knowledge.FieldUseCount, field.TypeInt, value)
		_node.UseCount = value
	}
	if value, ok := _c.mutation.RelevanceScore(); ok {
		_spec.SetField(knowledge.FieldRelevanceScore, field.TypeFloat64, value)
		_node.RelevanceScore = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(knowledge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// KnowledgeCreateBulk is the builder for creating many Knowledge entities in bulk.
type KnowledgeCreateBulk struct {
	config
	err      error
	builders []*KnowledgeCreate
}

// Save creates the Knowledge entities in the database.
func (_c *KnowledgeCreateBulk) Save(ctx context.Context) ([]*Knowledge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Knowledge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeCreateBulk) SaveX(ctx context.Context) []*Knowledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
