// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/message"
	"github.com/langowarny/lango/internal/ent/predicate"
	"github.com/langowarny/lango/internal/ent/schema"
	"github.com/langowarny/lango/internal/ent/session"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v string) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *string) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *MessageUpdate) SetTimestamp(v time.Time) *MessageUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableTimestamp(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetToolCalls sets the "tool_calls" field.
func (_u *MessageUpdate) SetToolCalls(v []schema.ToolCall) *MessageUpdate {
	_u.mutation.SetToolCalls(v)
	return _u
}

// AppendToolCalls appends value to the "tool_calls" field.
func (_u *MessageUpdate) AppendToolCalls(v []schema.ToolCall) *MessageUpdate {
	_u.mutation.AppendToolCalls(v)
	return _u
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (_u *MessageUpdate) ClearToolCalls() *MessageUpdate {
	_u.mutation.ClearToolCalls()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *MessageUpdate) SetAuthor(v string) *MessageUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableAuthor(v *string) *MessageUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *MessageUpdate) ClearAuthor() *MessageUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *MessageUpdate) SetSessionID(id int) *MessageUpdate {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetNillableSessionID sets the "session" edge to the Session entity by ID if the given value is not nil.
func (_u *MessageUpdate) SetNillableSessionID(id *int) *MessageUpdate {
	if id != nil {
		_u = _u.SetSessionID(*id)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MessageUpdate) SetSession(v *Session) *MessageUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MessageUpdate) ClearSession() *MessageUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(message.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ToolCalls(); ok {
		_spec.SetField(message.FieldToolCalls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolCalls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldToolCalls, value)
		})
	}
	if _u.mutation.ToolCallsCleared() {
		_spec.ClearField(message.FieldToolCalls, field.TypeJSON)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(message.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(message.FieldAuthor, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v string) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *MessageUpdateOne) SetTimestamp(v time.Time) *MessageUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableTimestamp(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetToolCalls sets the "tool_calls" field.
func (_u *MessageUpdateOne) SetToolCalls(v []schema.ToolCall) *MessageUpdateOne {
	_u.mutation.SetToolCalls(v)
	return _u
}

// AppendToolCalls appends value to the "tool_calls" field.
func (_u *MessageUpdateOne) AppendToolCalls(v []schema.ToolCall) *MessageUpdateOne {
	_u.mutation.AppendToolCalls(v)
	return _u
}

// ClearToolCalls clears the value of the "tool_calls" field.
func (_u *MessageUpdateOne) ClearToolCalls() *MessageUpdateOne {
	_u.mutation.ClearToolCalls()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *MessageUpdateOne) SetAuthor(v string) *MessageUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableAuthor(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *MessageUpdateOne) ClearAuthor() *MessageUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *MessageUpdateOne) SetSessionID(id int) *MessageUpdateOne {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetNillableSessionID sets the "session" edge to the Session entity by ID if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSessionID(id *int) *MessageUpdateOne {
	if id != nil {
		_u = _u.SetSessionID(*id)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *MessageUpdateOne) SetSession(v *Session) *MessageUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *MessageUpdateOne) ClearSession() *MessageUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(message.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ToolCalls(); ok {
		_spec.SetField(message.FieldToolCalls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolCalls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldToolCalls, value)
		})
	}
	if _u.mutation.ToolCallsCleared() {
		_spec.ClearField(message.FieldToolCalls, field.TypeJSON)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(message.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(message.FieldAuthor, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
