// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/observation"
)

// ObservationCreate is the builder for creating a Observation entity.
type ObservationCreate struct {
	config
	mutation *ObservationMutation
	hooks    []Hook
}

// SetSessionKey sets the "session_key" field.
func (_c *ObservationCreate) SetSessionKey(v string) *ObservationCreate {
	_c.mutation.SetSessionKey(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ObservationCreate) SetContent(v string) *ObservationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetTokenCount sets the "token_count" field.
func (_c *ObservationCreate) SetTokenCount(v int) *ObservationCreate {
	_c.mutation.SetTokenCount(v)
	return _c
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_c *ObservationCreate) SetNillableTokenCount(v *int) *ObservationCreate {
	if v != nil {
		_c.SetTokenCount(*v)
	}
	return _c
}

// SetSourceStartIndex sets the "source_start_index" field.
func (_c *ObservationCreate) SetSourceStartIndex(v int) *ObservationCreate {
	_c.mutation.SetSourceStartIndex(v)
	return _c
}

// SetNillableSourceStartIndex sets the "source_start_index" field if the given value is not nil.
func (_c *ObservationCreate) SetNillableSourceStartIndex(v *int) *ObservationCreate {
	if v != nil {
		_c.SetSourceStartIndex(*v)
	}
	return _c
}

// SetSourceEndIndex sets the "source_end_index" field.
func (_c *ObservationCreate) SetSourceEndIndex(v int) *ObservationCreate {
	_c.mutation.SetSourceEndIndex(v)
	return _c
}

// SetNillableSourceEndIndex sets the "source_end_index" field if the given value is not nil.
func (_c *ObservationCreate) SetNillableSourceEndIndex(v *int) *ObservationCreate {
	if v != nil {
		_c.SetSourceEndIndex(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObservationCreate) SetCreatedAt(v time.Time) *ObservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObservationCreate) SetNillableCreatedAt(v *time.Time) *ObservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ObservationCreate) SetID(v uuid.UUID) *ObservationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ObservationCreate) SetNillableID(v *uuid.UUID) *ObservationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ObservationMutation object of the builder.
func (_c *ObservationCreate) Mutation() *ObservationMutation {
	return _c.mutation
}

// Save creates the Observation in the database.
func (_c *ObservationCreate) Save(ctx context.Context) (*Observation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObservationCreate) SaveX(ctx context.Context) *Observation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObservationCreate) defaults() {
	if _, ok := _c.mutation.TokenCount(); !ok {
		v := observation.DefaultTokenCount
		_c.mutation.SetTokenCount(v)
	}
	if _, ok := _c.mutation.SourceStartIndex(); !ok {
		v := observation.DefaultSourceStartIndex
		_c.mutation.SetSourceStartIndex(v)
	}
	if _, ok := _c.mutation.SourceEndIndex(); !ok {
		v := observation.DefaultSourceEndIndex
		_c.mutation.SetSourceEndIndex(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := observation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := observation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObservationCreate) check() error {
	if _, ok := _c.mutation.SessionKey(); !ok {
		return &ValidationError{Name: "session_key", err: errors.New(`ent: missing required field "Observation.session_key"`)}
	}
	if v, ok := _c.mutation.SessionKey(); ok {
		if err := observation.SessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "session_key", err: fmt.Errorf(`ent: validator failed for field "Observation.session_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Observation.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := observation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Observation.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenCount(); !ok {
		return &ValidationError{Name: "token_count", err: errors.New(`ent: missing required field "Observation.token_count"`)}
	}
	if _, ok := _c.mutation.SourceStartIndex(); !ok {
		return &ValidationError{Name: "source_start_index", err: errors.New(`ent: missing required field "Observation.source_start_index"`)}
	}
	if _, ok := _c.mutation.SourceEndIndex(); !ok {
		return &ValidationError{Name: "source_end_index", err: errors.New(`ent: missing required field "Observation.source_end_index"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Observation.created_at"`)}
	}
	return nil
}

func (_c *ObservationCreate) sqlSave(ctx context.Context) (*Observation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObservationCreate) createSpec() (*Observation, *sqlgraph.CreateSpec) {
	var (
		_node = &Observation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(observation.Table, sqlgraph.NewFieldSpec(observation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionKey(); ok {
		_spec.SetField(observation.FieldSessionKey, field.TypeString, value)
		_node.SessionKey = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(observation.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.TokenCount(); ok {
		_spec.SetField(observation.FieldTokenCount, field.TypeInt, value)
		_node.TokenCount = value
	}
	if value, ok := _c.mutation.SourceStartIndex(); ok {
		_spec.SetField(observation.FieldSourceStartIndex, field.TypeInt, value)
		_node.SourceStartIndex = value
	}
	if value, ok := _c.mutation.SourceEndIndex(); ok {
		_spec.SetField(observation.FieldSourceEndIndex, field.TypeInt, value)
		_node.SourceEndIndex = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(observation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ObservationCreateBulk is the builder for creating many Observation entities in bulk.
type ObservationCreateBulk struct {
	config
	err      error
	builders []*ObservationCreate
}

// Save creates the Observation entities in the database.
func (_c *ObservationCreateBulk) Save(ctx context.Context) ([]*Observation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Observation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObservationCreateBulk) SaveX(ctx context.Context) []*Observation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
