// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/observation"
)

// Observation is the model entity for the Observation schema.
type Observation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionKey holds the value of the "session_key" field.
	SessionKey string `json:"session_key,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// TokenCount holds the value of the "token_count" field.
	TokenCount int `json:"token_count,omitempty"`
	// SourceStartIndex holds the value of the "source_start_index" field.
	SourceStartIndex int `json:"source_start_index,omitempty"`
	// SourceEndIndex holds the value of the "source_end_index" field.
	SourceEndIndex int `json:"source_end_index,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Observation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case observation.FieldTokenCount, observation.FieldSourceStartIndex, observation.FieldSourceEndIndex:
			values[i] = new(sql.NullInt64)
		case observation.FieldSessionKey, observation.FieldContent:
			values[i] = new(sql.NullString)
		case observation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case observation.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Observation fields.
func (_m *Observation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case observation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case observation.FieldSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_key", values[i])
			} else if value.Valid {
				_m.SessionKey = value.String
			}
		case observation.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case observation.FieldTokenCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_count", values[i])
			} else if value.Valid {
				_m.TokenCount = int(value.Int64)
			}
		case observation.FieldSourceStartIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_start_index", values[i])
			} else if value.Valid {
				_m.SourceStartIndex = int(value.Int64)
			}
		case observation.FieldSourceEndIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_end_index", values[i])
			} else if value.Valid {
				_m.SourceEndIndex = int(value.Int64)
			}
		case observation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Observation.
// This includes values selected through modifiers, order, etc.
func (_m *Observation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Observation.
// Note that you need to call Observation.Unwrap() before calling this method if this Observation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Observation) Update() *ObservationUpdateOne {
	return NewObservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Observation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Observation) Unwrap() *Observation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Observation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Observation) String() string {
	var builder strings.Builder
	builder.WriteString("Observation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_key=")
	builder.WriteString(_m.SessionKey)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("token_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenCount))
	builder.WriteString(", ")
	builder.WriteString("source_start_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceStartIndex))
	builder.WriteString(", ")
	builder.WriteString("source_end_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceEndIndex))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Observations is a parsable slice of Observation.
type Observations []*Observation
