// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/observation"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// ObservationUpdate is the builder for updating Observation entities.
type ObservationUpdate struct {
	config
	hooks    []Hook
	mutation *ObservationMutation
}

// Where appends a list predicates to the ObservationUpdate builder.
func (_u *ObservationUpdate) Where(ps ...predicate.Observation) *ObservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionKey sets the "session_key" field.
func (_u *ObservationUpdate) SetSessionKey(v string) *ObservationUpdate {
	_u.mutation.SetSessionKey(v)
	return _u
}

// SetNillableSessionKey sets the "session_key" field if the given value is not nil.
func (_u *ObservationUpdate) SetNillableSessionKey(v *string) *ObservationUpdate {
	if v != nil {
		_u.SetSessionKey(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ObservationUpdate) SetContent(v string) *ObservationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ObservationUpdate) SetNillableContent(v *string) *ObservationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *ObservationUpdate) SetTokenCount(v int) *ObservationUpdate {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *ObservationUpdate) SetNillableTokenCount(v *int) *ObservationUpdate {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *ObservationUpdate) AddTokenCount(v int) *ObservationUpdate {
	_u.mutation.AddTokenCount(v)
	return _u
}

// SetSourceStartIndex sets the "source_start_index" field.
func (_u *ObservationUpdate) SetSourceStartIndex(v int) *ObservationUpdate {
	_u.mutation.ResetSourceStartIndex()
	_u.mutation.SetSourceStartIndex(v)
	return _u
}

// SetNillableSourceStartIndex sets the "source_start_index" field if the given value is not nil.
func (_u *ObservationUpdate) SetNillableSourceStartIndex(v *int) *ObservationUpdate {
	if v != nil {
		_u.SetSourceStartIndex(*v)
	}
	return _u
}

// AddSourceStartIndex adds value to the "source_start_index" field.
func (_u *ObservationUpdate) AddSourceStartIndex(v int) *ObservationUpdate {
	_u.mutation.AddSourceStartIndex(v)
	return _u
}

// SetSourceEndIndex sets the "source_end_index" field.
func (_u *ObservationUpdate) SetSourceEndIndex(v int) *ObservationUpdate {
	_u.mutation.ResetSourceEndIndex()
	_u.mutation.SetSourceEndIndex(v)
	return _u
}

// SetNillableSourceEndIndex sets the "source_end_index" field if the given value is not nil.
func (_u *ObservationUpdate) SetNillableSourceEndIndex(v *int) *ObservationUpdate {
	if v != nil {
		_u.SetSourceEndIndex(*v)
	}
	return _u
}

// AddSourceEndIndex adds value to the "source_end_index" field.
func (_u *ObservationUpdate) AddSourceEndIndex(v int) *ObservationUpdate {
	_u.mutation.AddSourceEndIndex(v)
	return _u
}

// Mutation returns the ObservationMutation object of the builder.
func (_u *ObservationUpdate) Mutation() *ObservationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObservationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObservationUpdate) check() error {
	if v, ok := _u.mutation.SessionKey(); ok {
		if err := observation.SessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "session_key", err: fmt.Errorf(`ent: validator failed for field "Observation.session_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := observation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Observation.content": %w`, err)}
		}
	}
	return nil
}

func (_u *ObservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(observation.Table, observation.Columns, sqlgraph.NewFieldSpec(observation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionKey(); ok {
		_spec.SetField(observation.FieldSessionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(observation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(observation.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(observation.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceStartIndex(); ok {
		_spec.SetField(observation.FieldSourceStartIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceStartIndex(); ok {
		_spec.AddField(observation.FieldSourceStartIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceEndIndex(); ok {
		_spec.SetField(observation.FieldSourceEndIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceEndIndex(); ok {
		_spec.AddField(observation.FieldSourceEndIndex, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{observation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObservationUpdateOne is the builder for updating a single Observation entity.
type ObservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObservationMutation
}

// SetSessionKey sets the "session_key" field.
func (_u *ObservationUpdateOne) SetSessionKey(v string) *ObservationUpdateOne {
	_u.mutation.SetSessionKey(v)
	return _u
}

// SetNillableSessionKey sets the "session_key" field if the given value is not nil.
func (_u *ObservationUpdateOne) SetNillableSessionKey(v *string) *ObservationUpdateOne {
	if v != nil {
		_u.SetSessionKey(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ObservationUpdateOne) SetContent(v string) *ObservationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ObservationUpdateOne) SetNillableContent(v *string) *ObservationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *ObservationUpdateOne) SetTokenCount(v int) *ObservationUpdateOne {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *ObservationUpdateOne) SetNillableTokenCount(v *int) *ObservationUpdateOne {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *ObservationUpdateOne) AddTokenCount(v int) *ObservationUpdateOne {
	_u.mutation.AddTokenCount(v)
	return _u
}

// SetSourceStartIndex sets the "source_start_index" field.
func (_u *ObservationUpdateOne) SetSourceStartIndex(v int) *ObservationUpdateOne {
	_u.mutation.ResetSourceStartIndex()
	_u.mutation.SetSourceStartIndex(v)
	return _u
}

// SetNillableSourceStartIndex sets the "source_start_index" field if the given value is not nil.
func (_u *ObservationUpdateOne) SetNillableSourceStartIndex(v *int) *ObservationUpdateOne {
	if v != nil {
		_u.SetSourceStartIndex(*v)
	}
	return _u
}

// AddSourceStartIndex adds value to the "source_start_index" field.
func (_u *ObservationUpdateOne) AddSourceStartIndex(v int) *ObservationUpdateOne {
	_u.mutation.AddSourceStartIndex(v)
	return _u
}

// SetSourceEndIndex sets the "source_end_index" field.
func (_u *ObservationUpdateOne) SetSourceEndIndex(v int) *ObservationUpdateOne {
	_u.mutation.ResetSourceEndIndex()
	_u.mutation.SetSourceEndIndex(v)
	return _u
}

// SetNillableSourceEndIndex sets the "source_end_index" field if the given value is not nil.
func (_u *ObservationUpdateOne) SetNillableSourceEndIndex(v *int) *ObservationUpdateOne {
	if v != nil {
		_u.SetSourceEndIndex(*v)
	}
	return _u
}

// AddSourceEndIndex adds value to the "source_end_index" field.
func (_u *ObservationUpdateOne) AddSourceEndIndex(v int) *ObservationUpdateOne {
	_u.mutation.AddSourceEndIndex(v)
	return _u
}

// Mutation returns the ObservationMutation object of the builder.
func (_u *ObservationUpdateOne) Mutation() *ObservationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ObservationUpdate builder.
func (_u *ObservationUpdateOne) Where(ps ...predicate.Observation) *ObservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObservationUpdateOne) Select(field string, fields ...string) *ObservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Observation entity.
func (_u *ObservationUpdateOne) Save(ctx context.Context) (*Observation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObservationUpdateOne) SaveX(ctx context.Context) *Observation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObservationUpdateOne) check() error {
	if v, ok := _u.mutation.SessionKey(); ok {
		if err := observation.SessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "session_key", err: fmt.Errorf(`ent: validator failed for field "Observation.session_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := observation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Observation.content": %w`, err)}
		}
	}
	return nil
}

func (_u *ObservationUpdateOne) sqlSave(ctx context.Context) (_node *Observation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(observation.Table, observation.Columns, sqlgraph.NewFieldSpec(observation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Observation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, observation.FieldID)
		for _, f := range fields {
			if !observation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != observation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionKey(); ok {
		_spec.SetField(observation.FieldSessionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(observation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(observation.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(observation.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceStartIndex(); ok {
		_spec.SetField(observation.FieldSourceStartIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceStartIndex(); ok {
		_spec.AddField(observation.FieldSourceStartIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceEndIndex(); ok {
		_spec.SetField(observation.FieldSourceEndIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceEndIndex(); ok {
		_spec.AddField(observation.FieldSourceEndIndex, field.TypeInt, value)
	}
	_node = &Observation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{observation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
