// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/paymenttx"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// PaymentTxUpdate is the builder for updating PaymentTx entities.
type PaymentTxUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentTxMutation
}

// Where appends a list predicates to the PaymentTxUpdate builder.
func (_u *PaymentTxUpdate) Where(ps ...predicate.PaymentTx) *PaymentTxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *PaymentTxUpdate) SetTxHash(v string) *PaymentTxUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableTxHash(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *PaymentTxUpdate) ClearTxHash() *PaymentTxUpdate {
	_u.mutation.ClearTxHash()
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *PaymentTxUpdate) SetFromAddress(v string) *PaymentTxUpdate {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableFromAddress(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetToAddress sets the "to_address" field.
func (_u *PaymentTxUpdate) SetToAddress(v string) *PaymentTxUpdate {
	_u.mutation.SetToAddress(v)
	return _u
}

// SetNillableToAddress sets the "to_address" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableToAddress(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetToAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentTxUpdate) SetAmount(v string) *PaymentTxUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableAmount(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *PaymentTxUpdate) SetChainID(v int64) *PaymentTxUpdate {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableChainID(v *int64) *PaymentTxUpdate {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *PaymentTxUpdate) AddChainID(v int64) *PaymentTxUpdate {
	_u.mutation.AddChainID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentTxUpdate) SetStatus(v paymenttx.Status) *PaymentTxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableStatus(v *paymenttx.Status) *PaymentTxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSessionKey sets the "session_key" field.
func (_u *PaymentTxUpdate) SetSessionKey(v string) *PaymentTxUpdate {
	_u.mutation.SetSessionKey(v)
	return _u
}

// SetNillableSessionKey sets the "session_key" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableSessionKey(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetSessionKey(*v)
	}
	return _u
}

// ClearSessionKey clears the value of the "session_key" field.
func (_u *PaymentTxUpdate) ClearSessionKey() *PaymentTxUpdate {
	_u.mutation.ClearSessionKey()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *PaymentTxUpdate) SetPurpose(v string) *PaymentTxUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillablePurpose(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// ClearPurpose clears the value of the "purpose" field.
func (_u *PaymentTxUpdate) ClearPurpose() *PaymentTxUpdate {
	_u.mutation.ClearPurpose()
	return _u
}

// SetX402URL sets the "x402_url" field.
func (_u *PaymentTxUpdate) SetX402URL(v string) *PaymentTxUpdate {
	_u.mutation.SetX402URL(v)
	return _u
}

// SetNillableX402URL sets the "x402_url" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableX402URL(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetX402URL(*v)
	}
	return _u
}

// ClearX402URL clears the value of the "x402_url" field.
func (_u *PaymentTxUpdate) ClearX402URL() *PaymentTxUpdate {
	_u.mutation.ClearX402URL()
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *PaymentTxUpdate) SetPaymentMethod(v paymenttx.PaymentMethod) *PaymentTxUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillablePaymentMethod(v *paymenttx.PaymentMethod) *PaymentTxUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PaymentTxUpdate) SetErrorMessage(v string) *PaymentTxUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PaymentTxUpdate) SetNillableErrorMessage(v *string) *PaymentTxUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PaymentTxUpdate) ClearErrorMessage() *PaymentTxUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentTxUpdate) SetUpdatedAt(v time.Time) *PaymentTxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentTxMutation object of the builder.
func (_u *PaymentTxUpdate) Mutation() *PaymentTxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentTxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentTxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentTxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentTxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentTxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymenttx.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentTxUpdate) check() error {
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := paymenttx.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToAddress(); ok {
		if err := paymenttx.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.to_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymenttx.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymenttx.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := paymenttx.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.payment_method": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentTxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymenttx.Table, paymenttx.Columns, sqlgraph.NewFieldSpec(paymenttx.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(paymenttx.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(paymenttx.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(paymenttx.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAddress(); ok {
		_spec.SetField(paymenttx.FieldToAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymenttx.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(paymenttx.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(paymenttx.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymenttx.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionKey(); ok {
		_spec.SetField(paymenttx.FieldSessionKey, field.TypeString, value)
	}
	if _u.mutation.SessionKeyCleared() {
		_spec.ClearField(paymenttx.FieldSessionKey, field.TypeString)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(paymenttx.FieldPurpose, field.TypeString, value)
	}
	if _u.mutation.PurposeCleared() {
		_spec.ClearField(paymenttx.FieldPurpose, field.TypeString)
	}
	if value, ok := _u.mutation.X402URL(); ok {
		_spec.SetField(paymenttx.FieldX402URL, field.TypeString, value)
	}
	if _u.mutation.X402URLCleared() {
		_spec.ClearField(paymenttx.FieldX402URL, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(paymenttx.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(paymenttx.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(paymenttx.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymenttx.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymenttx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentTxUpdateOne is the builder for updating a single PaymentTx entity.
type PaymentTxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentTxMutation
}

// SetTxHash sets the "tx_hash" field.
func (_u *PaymentTxUpdateOne) SetTxHash(v string) *PaymentTxUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableTxHash(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *PaymentTxUpdateOne) ClearTxHash() *PaymentTxUpdateOne {
	_u.mutation.ClearTxHash()
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *PaymentTxUpdateOne) SetFromAddress(v string) *PaymentTxUpdateOne {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableFromAddress(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetToAddress sets the "to_address" field.
func (_u *PaymentTxUpdateOne) SetToAddress(v string) *PaymentTxUpdateOne {
	_u.mutation.SetToAddress(v)
	return _u
}

// SetNillableToAddress sets the "to_address" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableToAddress(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetToAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentTxUpdateOne) SetAmount(v string) *PaymentTxUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableAmount(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetChainID sets the "chain_id" field.
func (_u *PaymentTxUpdateOne) SetChainID(v int64) *PaymentTxUpdateOne {
	_u.mutation.ResetChainID()
	_u.mutation.SetChainID(v)
	return _u
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableChainID(v *int64) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetChainID(*v)
	}
	return _u
}

// AddChainID adds value to the "chain_id" field.
func (_u *PaymentTxUpdateOne) AddChainID(v int64) *PaymentTxUpdateOne {
	_u.mutation.AddChainID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentTxUpdateOne) SetStatus(v paymenttx.Status) *PaymentTxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableStatus(v *paymenttx.Status) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSessionKey sets the "session_key" field.
func (_u *PaymentTxUpdateOne) SetSessionKey(v string) *PaymentTxUpdateOne {
	_u.mutation.SetSessionKey(v)
	return _u
}

// SetNillableSessionKey sets the "session_key" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableSessionKey(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetSessionKey(*v)
	}
	return _u
}

// ClearSessionKey clears the value of the "session_key" field.
func (_u *PaymentTxUpdateOne) ClearSessionKey() *PaymentTxUpdateOne {
	_u.mutation.ClearSessionKey()
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *PaymentTxUpdateOne) SetPurpose(v string) *PaymentTxUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillablePurpose(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// ClearPurpose clears the value of the "purpose" field.
func (_u *PaymentTxUpdateOne) ClearPurpose() *PaymentTxUpdateOne {
	_u.mutation.ClearPurpose()
	return _u
}

// SetX402URL sets the "x402_url" field.
func (_u *PaymentTxUpdateOne) SetX402URL(v string) *PaymentTxUpdateOne {
	_u.mutation.SetX402URL(v)
	return _u
}

// SetNillableX402URL sets the "x402_url" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableX402URL(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetX402URL(*v)
	}
	return _u
}

// ClearX402URL clears the value of the "x402_url" field.
func (_u *PaymentTxUpdateOne) ClearX402URL() *PaymentTxUpdateOne {
	_u.mutation.ClearX402URL()
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *PaymentTxUpdateOne) SetPaymentMethod(v paymenttx.PaymentMethod) *PaymentTxUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillablePaymentMethod(v *paymenttx.PaymentMethod) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PaymentTxUpdateOne) SetErrorMessage(v string) *PaymentTxUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PaymentTxUpdateOne) SetNillableErrorMessage(v *string) *PaymentTxUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PaymentTxUpdateOne) ClearErrorMessage() *PaymentTxUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentTxUpdateOne) SetUpdatedAt(v time.Time) *PaymentTxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentTxMutation object of the builder.
func (_u *PaymentTxUpdateOne) Mutation() *PaymentTxMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentTxUpdate builder.
func (_u *PaymentTxUpdateOne) Where(ps ...predicate.PaymentTx) *PaymentTxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentTxUpdateOne) Select(field string, fields ...string) *PaymentTxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentTx entity.
func (_u *PaymentTxUpdateOne) Save(ctx context.Context) (*PaymentTx, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentTxUpdateOne) SaveX(ctx context.Context) *PaymentTx {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentTxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentTxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentTxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymenttx.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentTxUpdateOne) check() error {
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := paymenttx.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToAddress(); ok {
		if err := paymenttx.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.to_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymenttx.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymenttx.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := paymenttx.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentTx.payment_method": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentTxUpdateOne) sqlSave(ctx context.Context) (_node *PaymentTx, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymenttx.Table, paymenttx.Columns, sqlgraph.NewFieldSpec(paymenttx.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentTx.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymenttx.FieldID)
		for _, f := range fields {
			if !paymenttx.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymenttx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(paymenttx.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(paymenttx.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(paymenttx.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToAddress(); ok {
		_spec.SetField(paymenttx.FieldToAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymenttx.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChainID(); ok {
		_spec.SetField(paymenttx.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChainID(); ok {
		_spec.AddField(paymenttx.FieldChainID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymenttx.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionKey(); ok {
		_spec.SetField(paymenttx.FieldSessionKey, field.TypeString, value)
	}
	if _u.mutation.SessionKeyCleared() {
		_spec.ClearField(paymenttx.FieldSessionKey, field.TypeString)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(paymenttx.FieldPurpose, field.TypeString, value)
	}
	if _u.mutation.PurposeCleared() {
		_spec.ClearField(paymenttx.FieldPurpose, field.TypeString)
	}
	if value, ok := _u.mutation.X402URL(); ok {
		_spec.SetField(paymenttx.FieldX402URL, field.TypeString, value)
	}
	if _u.mutation.X402URLCleared() {
		_spec.ClearField(paymenttx.FieldX402URL, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(paymenttx.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(paymenttx.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(paymenttx.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymenttx.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentTx{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymenttx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
