// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/peerreputation"
)

// PeerReputationCreate is the builder for creating a PeerReputation entity.
type PeerReputationCreate struct {
	config
	mutation *PeerReputationMutation
	hooks    []Hook
}

// SetPeerDid sets the "peer_did" field.
func (_c *PeerReputationCreate) SetPeerDid(v string) *PeerReputationCreate {
	_c.mutation.SetPeerDid(v)
	return _c
}

// SetSuccessfulExchanges sets the "successful_exchanges" field.
func (_c *PeerReputationCreate) SetSuccessfulExchanges(v int) *PeerReputationCreate {
	_c.mutation.SetSuccessfulExchanges(v)
	return _c
}

// SetNillableSuccessfulExchanges sets the "successful_exchanges" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableSuccessfulExchanges(v *int) *PeerReputationCreate {
	if v != nil {
		_c.SetSuccessfulExchanges(*v)
	}
	return _c
}

// SetFailedExchanges sets the "failed_exchanges" field.
func (_c *PeerReputationCreate) SetFailedExchanges(v int) *PeerReputationCreate {
	_c.mutation.SetFailedExchanges(v)
	return _c
}

// SetNillableFailedExchanges sets the "failed_exchanges" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableFailedExchanges(v *int) *PeerReputationCreate {
	if v != nil {
		_c.SetFailedExchanges(*v)
	}
	return _c
}

// SetTimeoutCount sets the "timeout_count" field.
func (_c *PeerReputationCreate) SetTimeoutCount(v int) *PeerReputationCreate {
	_c.mutation.SetTimeoutCount(v)
	return _c
}

// SetNillableTimeoutCount sets the "timeout_count" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableTimeoutCount(v *int) *PeerReputationCreate {
	if v != nil {
		_c.SetTimeoutCount(*v)
	}
	return _c
}

// SetTrustScore sets the "trust_score" field.
func (_c *PeerReputationCreate) SetTrustScore(v float64) *PeerReputationCreate {
	_c.mutation.SetTrustScore(v)
	return _c
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableTrustScore(v *float64) *PeerReputationCreate {
	if v != nil {
		_c.SetTrustScore(*v)
	}
	return _c
}

// SetFirstSeen sets the "first_seen" field.
func (_c *PeerReputationCreate) SetFirstSeen(v time.Time) *PeerReputationCreate {
	_c.mutation.SetFirstSeen(v)
	return _c
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableFirstSeen(v *time.Time) *PeerReputationCreate {
	if v != nil {
		_c.SetFirstSeen(*v)
	}
	return _c
}

// SetLastInteraction sets the "last_interaction" field.
func (_c *PeerReputationCreate) SetLastInteraction(v time.Time) *PeerReputationCreate {
	_c.mutation.SetLastInteraction(v)
	return _c
}

// SetNillableLastInteraction sets the "last_interaction" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableLastInteraction(v *time.Time) *PeerReputationCreate {
	if v != nil {
		_c.SetLastInteraction(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PeerReputationCreate) SetCreatedAt(v time.Time) *PeerReputationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableCreatedAt(v *time.Time) *PeerReputationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PeerReputationCreate) SetUpdatedAt(v time.Time) *PeerReputationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableUpdatedAt(v *time.Time) *PeerReputationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PeerReputationCreate) SetID(v uuid.UUID) *PeerReputationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PeerReputationCreate) SetNillableID(v *uuid.UUID) *PeerReputationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PeerReputationMutation object of the builder.
func (_c *PeerReputationCreate) Mutation() *PeerReputationMutation {
	return _c.mutation
}

// Save creates the PeerReputation in the database.
func (_c *PeerReputationCreate) Save(ctx context.Context) (*PeerReputation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PeerReputationCreate) SaveX(ctx context.Context) *PeerReputation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PeerReputationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PeerReputationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PeerReputationCreate) defaults() {
	if _, ok := _c.mutation.SuccessfulExchanges(); !ok {
		v := peerreputation.DefaultSuccessfulExchanges
		_c.mutation.SetSuccessfulExchanges(v)
	}
	if _, ok := _c.mutation.FailedExchanges(); !ok {
		v := peerreputation.DefaultFailedExchanges
		_c.mutation.SetFailedExchanges(v)
	}
	if _, ok := _c.mutation.TimeoutCount(); !ok {
		v := peerreputation.DefaultTimeoutCount
		_c.mutation.SetTimeoutCount(v)
	}
	if _, ok := _c.mutation.TrustScore(); !ok {
		v := peerreputation.DefaultTrustScore
		_c.mutation.SetTrustScore(v)
	}
	if _, ok := _c.mutation.FirstSeen(); !ok {
		v := peerreputation.DefaultFirstSeen()
		_c.mutation.SetFirstSeen(v)
	}
	if _, ok := _c.mutation.LastInteraction(); !ok {
		v := peerreputation.DefaultLastInteraction()
		_c.mutation.SetLastInteraction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := peerreputation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := peerreputation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := peerreputation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PeerReputationCreate) check() error {
	if _, ok := _c.mutation.PeerDid(); !ok {
		return &ValidationError{Name: "peer_did", err: errors.New(`ent: missing required field "PeerReputation.peer_did"`)}
	}
	if v, ok := _c.mutation.PeerDid(); ok {
		if err := peerreputation.PeerDidValidator(v); err != nil {
			return &ValidationError{Name: "peer_did", err: fmt.Errorf(`ent: validator failed for field "PeerReputation.peer_did": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SuccessfulExchanges(); !ok {
		return &ValidationError{Name: "successful_exchanges", err: errors.New(`ent: missing required field "PeerReputation.successful_exchanges"`)}
	}
	if _, ok := _c.mutation.FailedExchanges(); !ok {
		return &ValidationError{Name: "failed_exchanges", err: errors.New(`ent: missing required field "PeerReputation.failed_exchanges"`)}
	}
	if _, ok := _c.mutation.TimeoutCount(); !ok {
		return &ValidationError{Name: "timeout_count", err: errors.New(`ent: missing required field "PeerReputation.timeout_count"`)}
	}
	if _, ok := _c.mutation.TrustScore(); !ok {
		return &ValidationError{Name: "trust_score", err: errors.New(`ent: missing required field "PeerReputation.trust_score"`)}
	}
	if _, ok := _c.mutation.FirstSeen(); !ok {
		return &ValidationError{Name: "first_seen", err: errors.New(`ent: missing required field "PeerReputation.first_seen"`)}
	}
	if _, ok := _c.mutation.LastInteraction(); !ok {
		return &ValidationError{Name: "last_interaction", err: errors.New(`ent: missing required field "PeerReputation.last_interaction"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PeerReputation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PeerReputation.updated_at"`)}
	}
	return nil
}

func (_c *PeerReputationCreate) sqlSave(ctx context.Context) (*PeerReputation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PeerReputationCreate) createSpec() (*PeerReputation, *sqlgraph.CreateSpec) {
	var (
		_node = &PeerReputation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(peerreputation.Table, sqlgraph.NewFieldSpec(peerreputation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PeerDid(); ok {
		_spec.SetField(peerreputation.FieldPeerDid, field.TypeString, value)
		_node.PeerDid = value
	}
	if value, ok := _c.mutation.SuccessfulExchanges(); ok {
		_spec.SetField(peerreputation.FieldSuccessfulExchanges, field.TypeInt, value)
		_node.SuccessfulExchanges = value
	}
	if value, ok := _c.mutation.FailedExchanges(); ok {
		_spec.SetField(peerreputation.FieldFailedExchanges, field.TypeInt, value)
		_node.FailedExchanges = value
	}
	if value, ok := _c.mutation.TimeoutCount(); ok {
		_spec.SetField(peerreputation.FieldTimeoutCount, field.TypeInt, value)
		_node.TimeoutCount = value
	}
	if value, ok := _c.mutation.TrustScore(); ok {
		_spec.SetField(peerreputation.FieldTrustScore, field.TypeFloat64, value)
		_node.TrustScore = value
	}
	if value, ok := _c.mutation.FirstSeen(); ok {
		_spec.SetField(peerreputation.FieldFirstSeen, field.TypeTime, value)
		_node.FirstSeen = value
	}
	if value, ok := _c.mutation.LastInteraction(); ok {
		_spec.SetField(peerreputation.FieldLastInteraction, field.TypeTime, value)
		_node.LastInteraction = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(peerreputation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(peerreputation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PeerReputationCreateBulk is the builder for creating many PeerReputation entities in bulk.
type PeerReputationCreateBulk struct {
	config
	err      error
	builders []*PeerReputationCreate
}

// Save creates the PeerReputation entities in the database.
func (_c *PeerReputationCreateBulk) Save(ctx context.Context) ([]*PeerReputation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PeerReputation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PeerReputationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PeerReputationCreateBulk) SaveX(ctx context.Context) []*PeerReputation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PeerReputationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PeerReputationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
