// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/peerreputation"
	"github.com/langoai/lango/internal/ent/predicate"
)

// PeerReputationUpdate is the builder for updating PeerReputation entities.
type PeerReputationUpdate struct {
	config
	hooks    []Hook
	mutation *PeerReputationMutation
}

// Where appends a list predicates to the PeerReputationUpdate builder.
func (_u *PeerReputationUpdate) Where(ps ...predicate.PeerReputation) *PeerReputationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPeerDid sets the "peer_did" field.
func (_u *PeerReputationUpdate) SetPeerDid(v string) *PeerReputationUpdate {
	_u.mutation.SetPeerDid(v)
	return _u
}

// SetNillablePeerDid sets the "peer_did" field if the given value is not nil.
func (_u *PeerReputationUpdate) SetNillablePeerDid(v *string) *PeerReputationUpdate {
	if v != nil {
		_u.SetPeerDid(*v)
	}
	return _u
}

// SetSuccessfulExchanges sets the "successful_exchanges" field.
func (_u *PeerReputationUpdate) SetSuccessfulExchanges(v int) *PeerReputationUpdate {
	_u.mutation.ResetSuccessfulExchanges()
	_u.mutation.SetSuccessfulExchanges(v)
	return _u
}

// SetNillableSuccessfulExchanges sets the "successful_exchanges" field if the given value is not nil.
func (_u *PeerReputationUpdate) SetNillableSuccessfulExchanges(v *int) *PeerReputationUpdate {
	if v != nil {
		_u.SetSuccessfulExchanges(*v)
	}
	return _u
}

// AddSuccessfulExchanges adds value to the "successful_exchanges" field.
func (_u *PeerReputationUpdate) AddSuccessfulExchanges(v int) *PeerReputationUpdate {
	_u.mutation.AddSuccessfulExchanges(v)
	return _u
}

// SetFailedExchanges sets the "failed_exchanges" field.
func (_u *PeerReputationUpdate) SetFailedExchanges(v int) *PeerReputationUpdate {
	_u.mutation.ResetFailedExchanges()
	_u.mutation.SetFailedExchanges(v)
	return _u
}

// SetNillableFailedExchanges sets the "failed_exchanges" field if the given value is not nil.
func (_u *PeerReputationUpdate) SetNillableFailedExchanges(v *int) *PeerReputationUpdate {
	if v != nil {
		_u.SetFailedExchanges(*v)
	}
	return _u
}

// AddFailedExchanges adds value to the "failed_exchanges" field.
func (_u *PeerReputationUpdate) AddFailedExchanges(v int) *PeerReputationUpdate {
	_u.mutation.AddFailedExchanges(v)
	return _u
}

// SetTimeoutCount sets the "timeout_count" field.
func (_u *PeerReputationUpdate) SetTimeoutCount(v int) *PeerReputationUpdate {
	_u.mutation.ResetTimeoutCount()
	_u.mutation.SetTimeoutCount(v)
	return _u
}

// SetNillableTimeoutCount sets the "timeout_count" field if the given value is not nil.
func (_u *PeerReputationUpdate) SetNillableTimeoutCount(v *int) *PeerReputationUpdate {
	if v != nil {
		_u.SetTimeoutCount(*v)
	}
	return _u
}

// AddTimeoutCount adds value to the "timeout_count" field.
func (_u *PeerReputationUpdate) AddTimeoutCount(v int) *PeerReputationUpdate {
	_u.mutation.AddTimeoutCount(v)
	return _u
}

// SetTrustScore sets the "trust_score" field.
func (_u *PeerReputationUpdate) SetTrustScore(v float64) *PeerReputationUpdate {
	_u.mutation.ResetTrustScore()
	_u.mutation.SetTrustScore(v)
	return _u
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_u *PeerReputationUpdate) SetNillableTrustScore(v *float64) *PeerReputationUpdate {
	if v != nil {
		_u.SetTrustScore(*v)
	}
	return _u
}

// AddTrustScore adds value to the "trust_score" field.
func (_u *PeerReputationUpdate) AddTrustScore(v float64) *PeerReputationUpdate {
	_u.mutation.AddTrustScore(v)
	return _u
}

// SetLastInteraction sets the "last_interaction" field.
func (_u *PeerReputationUpdate) SetLastInteraction(v time.Time) *PeerReputationUpdate {
	_u.mutation.SetLastInteraction(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PeerReputationUpdate) SetUpdatedAt(v time.Time) *PeerReputationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PeerReputationMutation object of the builder.
func (_u *PeerReputationUpdate) Mutation() *PeerReputationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PeerReputationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeerReputationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PeerReputationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeerReputationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeerReputationUpdate) defaults() {
	if _, ok := _u.mutation.LastInteraction(); !ok {
		v := peerreputation.UpdateDefaultLastInteraction()
		_u.mutation.SetLastInteraction(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := peerreputation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeerReputationUpdate) check() error {
	if v, ok := _u.mutation.PeerDid(); ok {
		if err := peerreputation.PeerDidValidator(v); err != nil {
			return &ValidationError{Name: "peer_did", err: fmt.Errorf(`ent: validator failed for field "PeerReputation.peer_did": %w`, err)}
		}
	}
	return nil
}

func (_u *PeerReputationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(peerreputation.Table, peerreputation.Columns, sqlgraph.NewFieldSpec(peerreputation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PeerDid(); ok {
		_spec.SetField(peerreputation.FieldPeerDid, field.TypeString, value)
	}
	if value, ok := _u.mutation.SuccessfulExchanges(); ok {
		_spec.SetField(peerreputation.FieldSuccessfulExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulExchanges(); ok {
		_spec.AddField(peerreputation.FieldSuccessfulExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedExchanges(); ok {
		_spec.SetField(peerreputation.FieldFailedExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedExchanges(); ok {
		_spec.AddField(peerreputation.FieldFailedExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutCount(); ok {
		_spec.SetField(peerreputation.FieldTimeoutCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutCount(); ok {
		_spec.AddField(peerreputation.FieldTimeoutCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrustScore(); ok {
		_spec.SetField(peerreputation.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrustScore(); ok {
		_spec.AddField(peerreputation.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastInteraction(); ok {
		_spec.SetField(peerreputation.FieldLastInteraction, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(peerreputation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{peerreputation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PeerReputationUpdateOne is the builder for updating a single PeerReputation entity.
type PeerReputationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PeerReputationMutation
}

// SetPeerDid sets the "peer_did" field.
func (_u *PeerReputationUpdateOne) SetPeerDid(v string) *PeerReputationUpdateOne {
	_u.mutation.SetPeerDid(v)
	return _u
}

// SetNillablePeerDid sets the "peer_did" field if the given value is not nil.
func (_u *PeerReputationUpdateOne) SetNillablePeerDid(v *string) *PeerReputationUpdateOne {
	if v != nil {
		_u.SetPeerDid(*v)
	}
	return _u
}

// SetSuccessfulExchanges sets the "successful_exchanges" field.
func (_u *PeerReputationUpdateOne) SetSuccessfulExchanges(v int) *PeerReputationUpdateOne {
	_u.mutation.ResetSuccessfulExchanges()
	_u.mutation.SetSuccessfulExchanges(v)
	return _u
}

// SetNillableSuccessfulExchanges sets the "successful_exchanges" field if the given value is not nil.
func (_u *PeerReputationUpdateOne) SetNillableSuccessfulExchanges(v *int) *PeerReputationUpdateOne {
	if v != nil {
		_u.SetSuccessfulExchanges(*v)
	}
	return _u
}

// AddSuccessfulExchanges adds value to the "successful_exchanges" field.
func (_u *PeerReputationUpdateOne) AddSuccessfulExchanges(v int) *PeerReputationUpdateOne {
	_u.mutation.AddSuccessfulExchanges(v)
	return _u
}

// SetFailedExchanges sets the "failed_exchanges" field.
func (_u *PeerReputationUpdateOne) SetFailedExchanges(v int) *PeerReputationUpdateOne {
	_u.mutation.ResetFailedExchanges()
	_u.mutation.SetFailedExchanges(v)
	return _u
}

// SetNillableFailedExchanges sets the "failed_exchanges" field if the given value is not nil.
func (_u *PeerReputationUpdateOne) SetNillableFailedExchanges(v *int) *PeerReputationUpdateOne {
	if v != nil {
		_u.SetFailedExchanges(*v)
	}
	return _u
}

// AddFailedExchanges adds value to the "failed_exchanges" field.
func (_u *PeerReputationUpdateOne) AddFailedExchanges(v int) *PeerReputationUpdateOne {
	_u.mutation.AddFailedExchanges(v)
	return _u
}

// SetTimeoutCount sets the "timeout_count" field.
func (_u *PeerReputationUpdateOne) SetTimeoutCount(v int) *PeerReputationUpdateOne {
	_u.mutation.ResetTimeoutCount()
	_u.mutation.SetTimeoutCount(v)
	return _u
}

// SetNillableTimeoutCount sets the "timeout_count" field if the given value is not nil.
func (_u *PeerReputationUpdateOne) SetNillableTimeoutCount(v *int) *PeerReputationUpdateOne {
	if v != nil {
		_u.SetTimeoutCount(*v)
	}
	return _u
}

// AddTimeoutCount adds value to the "timeout_count" field.
func (_u *PeerReputationUpdateOne) AddTimeoutCount(v int) *PeerReputationUpdateOne {
	_u.mutation.AddTimeoutCount(v)
	return _u
}

// SetTrustScore sets the "trust_score" field.
func (_u *PeerReputationUpdateOne) SetTrustScore(v float64) *PeerReputationUpdateOne {
	_u.mutation.ResetTrustScore()
	_u.mutation.SetTrustScore(v)
	return _u
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_u *PeerReputationUpdateOne) SetNillableTrustScore(v *float64) *PeerReputationUpdateOne {
	if v != nil {
		_u.SetTrustScore(*v)
	}
	return _u
}

// AddTrustScore adds value to the "trust_score" field.
func (_u *PeerReputationUpdateOne) AddTrustScore(v float64) *PeerReputationUpdateOne {
	_u.mutation.AddTrustScore(v)
	return _u
}

// SetLastInteraction sets the "last_interaction" field.
func (_u *PeerReputationUpdateOne) SetLastInteraction(v time.Time) *PeerReputationUpdateOne {
	_u.mutation.SetLastInteraction(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PeerReputationUpdateOne) SetUpdatedAt(v time.Time) *PeerReputationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PeerReputationMutation object of the builder.
func (_u *PeerReputationUpdateOne) Mutation() *PeerReputationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PeerReputationUpdate builder.
func (_u *PeerReputationUpdateOne) Where(ps ...predicate.PeerReputation) *PeerReputationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PeerReputationUpdateOne) Select(field string, fields ...string) *PeerReputationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PeerReputation entity.
func (_u *PeerReputationUpdateOne) Save(ctx context.Context) (*PeerReputation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeerReputationUpdateOne) SaveX(ctx context.Context) *PeerReputation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PeerReputationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeerReputationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeerReputationUpdateOne) defaults() {
	if _, ok := _u.mutation.LastInteraction(); !ok {
		v := peerreputation.UpdateDefaultLastInteraction()
		_u.mutation.SetLastInteraction(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := peerreputation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeerReputationUpdateOne) check() error {
	if v, ok := _u.mutation.PeerDid(); ok {
		if err := peerreputation.PeerDidValidator(v); err != nil {
			return &ValidationError{Name: "peer_did", err: fmt.Errorf(`ent: validator failed for field "PeerReputation.peer_did": %w`, err)}
		}
	}
	return nil
}

func (_u *PeerReputationUpdateOne) sqlSave(ctx context.Context) (_node *PeerReputation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(peerreputation.Table, peerreputation.Columns, sqlgraph.NewFieldSpec(peerreputation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PeerReputation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, peerreputation.FieldID)
		for _, f := range fields {
			if !peerreputation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != peerreputation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PeerDid(); ok {
		_spec.SetField(peerreputation.FieldPeerDid, field.TypeString, value)
	}
	if value, ok := _u.mutation.SuccessfulExchanges(); ok {
		_spec.SetField(peerreputation.FieldSuccessfulExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulExchanges(); ok {
		_spec.AddField(peerreputation.FieldSuccessfulExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedExchanges(); ok {
		_spec.SetField(peerreputation.FieldFailedExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedExchanges(); ok {
		_spec.AddField(peerreputation.FieldFailedExchanges, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutCount(); ok {
		_spec.SetField(peerreputation.FieldTimeoutCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutCount(); ok {
		_spec.AddField(peerreputation.FieldTimeoutCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrustScore(); ok {
		_spec.SetField(peerreputation.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrustScore(); ok {
		_spec.AddField(peerreputation.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastInteraction(); ok {
		_spec.SetField(peerreputation.FieldLastInteraction, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(peerreputation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PeerReputation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{peerreputation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
