// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/auditlog"
	"github.com/langoai/lango/internal/ent/configprofile"
	"github.com/langoai/lango/internal/ent/cronjob"
	"github.com/langoai/lango/internal/ent/cronjobhistory"
	"github.com/langoai/lango/internal/ent/externalref"
	"github.com/langoai/lango/internal/ent/inquiry"
	"github.com/langoai/lango/internal/ent/key"
	"github.com/langoai/lango/internal/ent/knowledge"
	"github.com/langoai/lango/internal/ent/learning"
	"github.com/langoai/lango/internal/ent/message"
	"github.com/langoai/lango/internal/ent/observation"
	"github.com/langoai/lango/internal/ent/paymenttx"
	"github.com/langoai/lango/internal/ent/peerreputation"
	"github.com/langoai/lango/internal/ent/reflection"
	"github.com/langoai/lango/internal/ent/schema"
	"github.com/langoai/lango/internal/ent/secret"
	"github.com/langoai/lango/internal/ent/session"
	"github.com/langoai/lango/internal/ent/workflowrun"
	"github.com/langoai/lango/internal/ent/workflowsteprun"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescActor is the schema descriptor for actor field.
	auditlogDescActor := auditlogFields[3].Descriptor()
	// auditlog.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	auditlog.ActorValidator = auditlogDescActor.Validators[0].(func(string) error)
	// auditlogDescTimestamp is the schema descriptor for timestamp field.
	auditlogDescTimestamp := auditlogFields[6].Descriptor()
	// auditlog.DefaultTimestamp holds the default value on creation for the timestamp field.
	auditlog.DefaultTimestamp = auditlogDescTimestamp.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	configprofileFields := schema.ConfigProfile{}.Fields()
	_ = configprofileFields
	// configprofileDescName is the schema descriptor for name field.
	configprofileDescName := configprofileFields[1].Descriptor()
	// configprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	configprofile.NameValidator = configprofileDescName.Validators[0].(func(string) error)
	// configprofileDescActive is the schema descriptor for active field.
	configprofileDescActive := configprofileFields[3].Descriptor()
	// configprofile.DefaultActive holds the default value on creation for the active field.
	configprofile.DefaultActive = configprofileDescActive.Default.(bool)
	// configprofileDescVersion is the schema descriptor for version field.
	configprofileDescVersion := configprofileFields[4].Descriptor()
	// configprofile.DefaultVersion holds the default value on creation for the version field.
	configprofile.DefaultVersion = configprofileDescVersion.Default.(int)
	// configprofileDescCreatedAt is the schema descriptor for created_at field.
	configprofileDescCreatedAt := configprofileFields[5].Descriptor()
	// configprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	configprofile.DefaultCreatedAt = configprofileDescCreatedAt.Default.(func() time.Time)
	// configprofileDescUpdatedAt is the schema descriptor for updated_at field.
	configprofileDescUpdatedAt := configprofileFields[6].Descriptor()
	// configprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configprofile.DefaultUpdatedAt = configprofileDescUpdatedAt.Default.(func() time.Time)
	// configprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configprofile.UpdateDefaultUpdatedAt = configprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// configprofileDescID is the schema descriptor for id field.
	configprofileDescID := configprofileFields[0].Descriptor()
	// configprofile.DefaultID holds the default value on creation for the id field.
	configprofile.DefaultID = configprofileDescID.Default.(func() uuid.UUID)
	cronjobFields := schema.CronJob{}.Fields()
	_ = cronjobFields
	// cronjobDescName is the schema descriptor for name field.
	cronjobDescName := cronjobFields[1].Descriptor()
	// cronjob.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cronjob.NameValidator = cronjobDescName.Validators[0].(func(string) error)
	// cronjobDescSchedule is the schema descriptor for schedule field.
	cronjobDescSchedule := cronjobFields[3].Descriptor()
	// cronjob.ScheduleValidator is a validator for the "schedule" field. It is called by the builders before save.
	cronjob.ScheduleValidator = cronjobDescSchedule.Validators[0].(func(string) error)
	// cronjobDescPrompt is the schema descriptor for prompt field.
	cronjobDescPrompt := cronjobFields[4].Descriptor()
	// cronjob.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	cronjob.PromptValidator = cronjobDescPrompt.Validators[0].(func(string) error)
	// cronjobDescSessionMode is the schema descriptor for session_mode field.
	cronjobDescSessionMode := cronjobFields[5].Descriptor()
	// cronjob.DefaultSessionMode holds the default value on creation for the session_mode field.
	cronjob.DefaultSessionMode = cronjobDescSessionMode.Default.(string)
	// cronjobDescTimezone is the schema descriptor for timezone field.
	cronjobDescTimezone := cronjobFields[7].Descriptor()
	// cronjob.DefaultTimezone holds the default value on creation for the timezone field.
	cronjob.DefaultTimezone = cronjobDescTimezone.Default.(string)
	// cronjobDescEnabled is the schema descriptor for enabled field.
	cronjobDescEnabled := cronjobFields[8].Descriptor()
	// cronjob.DefaultEnabled holds the default value on creation for the enabled field.
	cronjob.DefaultEnabled = cronjobDescEnabled.Default.(bool)
	// cronjobDescCreatedAt is the schema descriptor for created_at field.
	cronjobDescCreatedAt := cronjobFields[11].Descriptor()
	// cronjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	cronjob.DefaultCreatedAt = cronjobDescCreatedAt.Default.(func() time.Time)
	// cronjobDescUpdatedAt is the schema descriptor for updated_at field.
	cronjobDescUpdatedAt := cronjobFields[12].Descriptor()
	// cronjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cronjob.DefaultUpdatedAt = cronjobDescUpdatedAt.Default.(func() time.Time)
	// cronjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cronjob.UpdateDefaultUpdatedAt = cronjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cronjobDescID is the schema descriptor for id field.
	cronjobDescID := cronjobFields[0].Descriptor()
	// cronjob.DefaultID holds the default value on creation for the id field.
	cronjob.DefaultID = cronjobDescID.Default.(func() uuid.UUID)
	cronjobhistoryFields := schema.CronJobHistory{}.Fields()
	_ = cronjobhistoryFields
	// cronjobhistoryDescJobName is the schema descriptor for job_name field.
	cronjobhistoryDescJobName := cronjobhistoryFields[2].Descriptor()
	// cronjobhistory.JobNameValidator is a validator for the "job_name" field. It is called by the builders before save.
	cronjobhistory.JobNameValidator = cronjobhistoryDescJobName.Validators[0].(func(string) error)
	// cronjobhistoryDescTokensUsed is the schema descriptor for tokens_used field.
	cronjobhistoryDescTokensUsed := cronjobhistoryFields[7].Descriptor()
	// cronjobhistory.DefaultTokensUsed holds the default value on creation for the tokens_used field.
	cronjobhistory.DefaultTokensUsed = cronjobhistoryDescTokensUsed.Default.(int)
	// cronjobhistoryDescStartedAt is the schema descriptor for started_at field.
	cronjobhistoryDescStartedAt := cronjobhistoryFields[8].Descriptor()
	// cronjobhistory.DefaultStartedAt holds the default value on creation for the started_at field.
	cronjobhistory.DefaultStartedAt = cronjobhistoryDescStartedAt.Default.(func() time.Time)
	// cronjobhistoryDescID is the schema descriptor for id field.
	cronjobhistoryDescID := cronjobhistoryFields[0].Descriptor()
	// cronjobhistory.DefaultID holds the default value on creation for the id field.
	cronjobhistory.DefaultID = cronjobhistoryDescID.Default.(func() uuid.UUID)
	externalrefFields := schema.ExternalRef{}.Fields()
	_ = externalrefFields
	// externalrefDescName is the schema descriptor for name field.
	externalrefDescName := externalrefFields[1].Descriptor()
	// externalref.NameValidator is a validator for the "name" field. It is called by the builders before save.
	externalref.NameValidator = externalrefDescName.Validators[0].(func(string) error)
	// externalrefDescLocation is the schema descriptor for location field.
	externalrefDescLocation := externalrefFields[3].Descriptor()
	// externalref.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	externalref.LocationValidator = externalrefDescLocation.Validators[0].(func(string) error)
	// externalrefDescCreatedAt is the schema descriptor for created_at field.
	externalrefDescCreatedAt := externalrefFields[6].Descriptor()
	// externalref.DefaultCreatedAt holds the default value on creation for the created_at field.
	externalref.DefaultCreatedAt = externalrefDescCreatedAt.Default.(func() time.Time)
	// externalrefDescUpdatedAt is the schema descriptor for updated_at field.
	externalrefDescUpdatedAt := externalrefFields[7].Descriptor()
	// externalref.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	externalref.DefaultUpdatedAt = externalrefDescUpdatedAt.Default.(func() time.Time)
	// externalref.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	externalref.UpdateDefaultUpdatedAt = externalrefDescUpdatedAt.UpdateDefault.(func() time.Time)
	// externalrefDescID is the schema descriptor for id field.
	externalrefDescID := externalrefFields[0].Descriptor()
	// externalref.DefaultID holds the default value on creation for the id field.
	externalref.DefaultID = externalrefDescID.Default.(func() uuid.UUID)
	inquiryFields := schema.Inquiry{}.Fields()
	_ = inquiryFields
	// inquiryDescSessionKey is the schema descriptor for session_key field.
	inquiryDescSessionKey := inquiryFields[1].Descriptor()
	// inquiry.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	inquiry.SessionKeyValidator = inquiryDescSessionKey.Validators[0].(func(string) error)
	// inquiryDescTopic is the schema descriptor for topic field.
	inquiryDescTopic := inquiryFields[2].Descriptor()
	// inquiry.TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	inquiry.TopicValidator = inquiryDescTopic.Validators[0].(func(string) error)
	// inquiryDescQuestion is the schema descriptor for question field.
	inquiryDescQuestion := inquiryFields[3].Descriptor()
	// inquiry.QuestionValidator is a validator for the "question" field. It is called by the builders before save.
	inquiry.QuestionValidator = inquiryDescQuestion.Validators[0].(func(string) error)
	// inquiryDescCreatedAt is the schema descriptor for created_at field.
	inquiryDescCreatedAt := inquiryFields[10].Descriptor()
	// inquiry.DefaultCreatedAt holds the default value on creation for the created_at field.
	inquiry.DefaultCreatedAt = inquiryDescCreatedAt.Default.(func() time.Time)
	// inquiryDescID is the schema descriptor for id field.
	inquiryDescID := inquiryFields[0].Descriptor()
	// inquiry.DefaultID holds the default value on creation for the id field.
	inquiry.DefaultID = inquiryDescID.Default.(func() uuid.UUID)
	keyFields := schema.Key{}.Fields()
	_ = keyFields
	// keyDescName is the schema descriptor for name field.
	keyDescName := keyFields[1].Descriptor()
	// key.NameValidator is a validator for the "name" field. It is called by the builders before save.
	key.NameValidator = keyDescName.Validators[0].(func(string) error)
	// keyDescRemoteKeyID is the schema descriptor for remote_key_id field.
	keyDescRemoteKeyID := keyFields[2].Descriptor()
	// key.RemoteKeyIDValidator is a validator for the "remote_key_id" field. It is called by the builders before save.
	key.RemoteKeyIDValidator = keyDescRemoteKeyID.Validators[0].(func(string) error)
	// keyDescCreatedAt is the schema descriptor for created_at field.
	keyDescCreatedAt := keyFields[4].Descriptor()
	// key.DefaultCreatedAt holds the default value on creation for the created_at field.
	key.DefaultCreatedAt = keyDescCreatedAt.Default.(func() time.Time)
	// keyDescID is the schema descriptor for id field.
	keyDescID := keyFields[0].Descriptor()
	// key.DefaultID holds the default value on creation for the id field.
	key.DefaultID = keyDescID.Default.(func() uuid.UUID)
	knowledgeFields := schema.Knowledge{}.Fields()
	_ = knowledgeFields
	// knowledgeDescKey is the schema descriptor for key field.
	knowledgeDescKey := knowledgeFields[1].Descriptor()
	// knowledge.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	knowledge.KeyValidator = knowledgeDescKey.Validators[0].(func(string) error)
	// knowledgeDescContent is the schema descriptor for content field.
	knowledgeDescContent := knowledgeFields[3].Descriptor()
	// knowledge.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	knowledge.ContentValidator = knowledgeDescContent.Validators[0].(func(string) error)
	// knowledgeDescUseCount is the schema descriptor for use_count field.
	knowledgeDescUseCount := knowledgeFields[6].Descriptor()
	// knowledge.DefaultUseCount holds the default value on creation for the use_count field.
	knowledge.DefaultUseCount = knowledgeDescUseCount.Default.(int)
	// knowledgeDescRelevanceScore is the schema descriptor for relevance_score field.
	knowledgeDescRelevanceScore := knowledgeFields[7].Descriptor()
	// knowledge.DefaultRelevanceScore holds the default value on creation for the relevance_score field.
	knowledge.DefaultRelevanceScore = knowledgeDescRelevanceScore.Default.(float64)
	// knowledgeDescCreatedAt is the schema descriptor for created_at field.
	knowledgeDescCreatedAt := knowledgeFields[8].Descriptor()
	// knowledge.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledge.DefaultCreatedAt = knowledgeDescCreatedAt.Default.(func() time.Time)
	// knowledgeDescUpdatedAt is the schema descriptor for updated_at field.
	knowledgeDescUpdatedAt := knowledgeFields[9].Descriptor()
	// knowledge.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	knowledge.DefaultUpdatedAt = knowledgeDescUpdatedAt.Default.(func() time.Time)
	// knowledge.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	knowledge.UpdateDefaultUpdatedAt = knowledgeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// knowledgeDescID is the schema descriptor for id field.
	knowledgeDescID := knowledgeFields[0].Descriptor()
	// knowledge.DefaultID holds the default value on creation for the id field.
	knowledge.DefaultID = knowledgeDescID.Default.(func() uuid.UUID)
	learningFields := schema.Learning{}.Fields()
	_ = learningFields
	// learningDescTrigger is the schema descriptor for trigger field.
	learningDescTrigger := learningFields[1].Descriptor()
	// learning.TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	learning.TriggerValidator = learningDescTrigger.Validators[0].(func(string) error)
	// learningDescOccurrenceCount is the schema descriptor for occurrence_count field.
	learningDescOccurrenceCount := learningFields[7].Descriptor()
	// learning.DefaultOccurrenceCount holds the default value on creation for the occurrence_count field.
	learning.DefaultOccurrenceCount = learningDescOccurrenceCount.Default.(int)
	// learningDescSuccessCount is the schema descriptor for success_count field.
	learningDescSuccessCount := learningFields[8].Descriptor()
	// learning.DefaultSuccessCount holds the default value on creation for the success_count field.
	learning.DefaultSuccessCount = learningDescSuccessCount.Default.(int)
	// learningDescConfidence is the schema descriptor for confidence field.
	learningDescConfidence := learningFields[9].Descriptor()
	// learning.DefaultConfidence holds the default value on creation for the confidence field.
	learning.DefaultConfidence = learningDescConfidence.Default.(float64)
	// learningDescCreatedAt is the schema descriptor for created_at field.
	learningDescCreatedAt := learningFields[10].Descriptor()
	// learning.DefaultCreatedAt holds the default value on creation for the created_at field.
	learning.DefaultCreatedAt = learningDescCreatedAt.Default.(func() time.Time)
	// learningDescUpdatedAt is the schema descriptor for updated_at field.
	learningDescUpdatedAt := learningFields[11].Descriptor()
	// learning.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	learning.DefaultUpdatedAt = learningDescUpdatedAt.Default.(func() time.Time)
	// learning.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	learning.UpdateDefaultUpdatedAt = learningDescUpdatedAt.UpdateDefault.(func() time.Time)
	// learningDescID is the schema descriptor for id field.
	learningDescID := learningFields[0].Descriptor()
	// learning.DefaultID holds the default value on creation for the id field.
	learning.DefaultID = learningDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescRole is the schema descriptor for role field.
	messageDescRole := messageFields[0].Descriptor()
	// message.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	message.RoleValidator = messageDescRole.Validators[0].(func(string) error)
	// messageDescTimestamp is the schema descriptor for timestamp field.
	messageDescTimestamp := messageFields[2].Descriptor()
	// message.DefaultTimestamp holds the default value on creation for the timestamp field.
	message.DefaultTimestamp = messageDescTimestamp.Default.(func() time.Time)
	// messageDescAuthor is the schema descriptor for author field.
	messageDescAuthor := messageFields[4].Descriptor()
	// message.DefaultAuthor holds the default value on creation for the author field.
	message.DefaultAuthor = messageDescAuthor.Default.(string)
	observationFields := schema.Observation{}.Fields()
	_ = observationFields
	// observationDescSessionKey is the schema descriptor for session_key field.
	observationDescSessionKey := observationFields[1].Descriptor()
	// observation.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	observation.SessionKeyValidator = observationDescSessionKey.Validators[0].(func(string) error)
	// observationDescContent is the schema descriptor for content field.
	observationDescContent := observationFields[2].Descriptor()
	// observation.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	observation.ContentValidator = observationDescContent.Validators[0].(func(string) error)
	// observationDescTokenCount is the schema descriptor for token_count field.
	observationDescTokenCount := observationFields[3].Descriptor()
	// observation.DefaultTokenCount holds the default value on creation for the token_count field.
	observation.DefaultTokenCount = observationDescTokenCount.Default.(int)
	// observationDescSourceStartIndex is the schema descriptor for source_start_index field.
	observationDescSourceStartIndex := observationFields[4].Descriptor()
	// observation.DefaultSourceStartIndex holds the default value on creation for the source_start_index field.
	observation.DefaultSourceStartIndex = observationDescSourceStartIndex.Default.(int)
	// observationDescSourceEndIndex is the schema descriptor for source_end_index field.
	observationDescSourceEndIndex := observationFields[5].Descriptor()
	// observation.DefaultSourceEndIndex holds the default value on creation for the source_end_index field.
	observation.DefaultSourceEndIndex = observationDescSourceEndIndex.Default.(int)
	// observationDescCreatedAt is the schema descriptor for created_at field.
	observationDescCreatedAt := observationFields[6].Descriptor()
	// observation.DefaultCreatedAt holds the default value on creation for the created_at field.
	observation.DefaultCreatedAt = observationDescCreatedAt.Default.(func() time.Time)
	// observationDescID is the schema descriptor for id field.
	observationDescID := observationFields[0].Descriptor()
	// observation.DefaultID holds the default value on creation for the id field.
	observation.DefaultID = observationDescID.Default.(func() uuid.UUID)
	paymenttxFields := schema.PaymentTx{}.Fields()
	_ = paymenttxFields
	// paymenttxDescFromAddress is the schema descriptor for from_address field.
	paymenttxDescFromAddress := paymenttxFields[2].Descriptor()
	// paymenttx.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	paymenttx.FromAddressValidator = paymenttxDescFromAddress.Validators[0].(func(string) error)
	// paymenttxDescToAddress is the schema descriptor for to_address field.
	paymenttxDescToAddress := paymenttxFields[3].Descriptor()
	// paymenttx.ToAddressValidator is a validator for the "to_address" field. It is called by the builders before save.
	paymenttx.ToAddressValidator = paymenttxDescToAddress.Validators[0].(func(string) error)
	// paymenttxDescAmount is the schema descriptor for amount field.
	paymenttxDescAmount := paymenttxFields[4].Descriptor()
	// paymenttx.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	paymenttx.AmountValidator = paymenttxDescAmount.Validators[0].(func(string) error)
	// paymenttxDescCreatedAt is the schema descriptor for created_at field.
	paymenttxDescCreatedAt := paymenttxFields[12].Descriptor()
	// paymenttx.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymenttx.DefaultCreatedAt = paymenttxDescCreatedAt.Default.(func() time.Time)
	// paymenttxDescUpdatedAt is the schema descriptor for updated_at field.
	paymenttxDescUpdatedAt := paymenttxFields[13].Descriptor()
	// paymenttx.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymenttx.DefaultUpdatedAt = paymenttxDescUpdatedAt.Default.(func() time.Time)
	// paymenttx.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymenttx.UpdateDefaultUpdatedAt = paymenttxDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymenttxDescID is the schema descriptor for id field.
	paymenttxDescID := paymenttxFields[0].Descriptor()
	// paymenttx.DefaultID holds the default value on creation for the id field.
	paymenttx.DefaultID = paymenttxDescID.Default.(func() uuid.UUID)
	peerreputationFields := schema.PeerReputation{}.Fields()
	_ = peerreputationFields
	// peerreputationDescPeerDid is the schema descriptor for peer_did field.
	peerreputationDescPeerDid := peerreputationFields[1].Descriptor()
	// peerreputation.PeerDidValidator is a validator for the "peer_did" field. It is called by the builders before save.
	peerreputation.PeerDidValidator = peerreputationDescPeerDid.Validators[0].(func(string) error)
	// peerreputationDescSuccessfulExchanges is the schema descriptor for successful_exchanges field.
	peerreputationDescSuccessfulExchanges := peerreputationFields[2].Descriptor()
	// peerreputation.DefaultSuccessfulExchanges holds the default value on creation for the successful_exchanges field.
	peerreputation.DefaultSuccessfulExchanges = peerreputationDescSuccessfulExchanges.Default.(int)
	// peerreputationDescFailedExchanges is the schema descriptor for failed_exchanges field.
	peerreputationDescFailedExchanges := peerreputationFields[3].Descriptor()
	// peerreputation.DefaultFailedExchanges holds the default value on creation for the failed_exchanges field.
	peerreputation.DefaultFailedExchanges = peerreputationDescFailedExchanges.Default.(int)
	// peerreputationDescTimeoutCount is the schema descriptor for timeout_count field.
	peerreputationDescTimeoutCount := peerreputationFields[4].Descriptor()
	// peerreputation.DefaultTimeoutCount holds the default value on creation for the timeout_count field.
	peerreputation.DefaultTimeoutCount = peerreputationDescTimeoutCount.Default.(int)
	// peerreputationDescTrustScore is the schema descriptor for trust_score field.
	peerreputationDescTrustScore := peerreputationFields[5].Descriptor()
	// peerreputation.DefaultTrustScore holds the default value on creation for the trust_score field.
	peerreputation.DefaultTrustScore = peerreputationDescTrustScore.Default.(float64)
	// peerreputationDescFirstSeen is the schema descriptor for first_seen field.
	peerreputationDescFirstSeen := peerreputationFields[6].Descriptor()
	// peerreputation.DefaultFirstSeen holds the default value on creation for the first_seen field.
	peerreputation.DefaultFirstSeen = peerreputationDescFirstSeen.Default.(func() time.Time)
	// peerreputationDescLastInteraction is the schema descriptor for last_interaction field.
	peerreputationDescLastInteraction := peerreputationFields[7].Descriptor()
	// peerreputation.DefaultLastInteraction holds the default value on creation for the last_interaction field.
	peerreputation.DefaultLastInteraction = peerreputationDescLastInteraction.Default.(func() time.Time)
	// peerreputation.UpdateDefaultLastInteraction holds the default value on update for the last_interaction field.
	peerreputation.UpdateDefaultLastInteraction = peerreputationDescLastInteraction.UpdateDefault.(func() time.Time)
	// peerreputationDescCreatedAt is the schema descriptor for created_at field.
	peerreputationDescCreatedAt := peerreputationFields[8].Descriptor()
	// peerreputation.DefaultCreatedAt holds the default value on creation for the created_at field.
	peerreputation.DefaultCreatedAt = peerreputationDescCreatedAt.Default.(func() time.Time)
	// peerreputationDescUpdatedAt is the schema descriptor for updated_at field.
	peerreputationDescUpdatedAt := peerreputationFields[9].Descriptor()
	// peerreputation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	peerreputation.DefaultUpdatedAt = peerreputationDescUpdatedAt.Default.(func() time.Time)
	// peerreputation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	peerreputation.UpdateDefaultUpdatedAt = peerreputationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// peerreputationDescID is the schema descriptor for id field.
	peerreputationDescID := peerreputationFields[0].Descriptor()
	// peerreputation.DefaultID holds the default value on creation for the id field.
	peerreputation.DefaultID = peerreputationDescID.Default.(func() uuid.UUID)
	reflectionFields := schema.Reflection{}.Fields()
	_ = reflectionFields
	// reflectionDescSessionKey is the schema descriptor for session_key field.
	reflectionDescSessionKey := reflectionFields[1].Descriptor()
	// reflection.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	reflection.SessionKeyValidator = reflectionDescSessionKey.Validators[0].(func(string) error)
	// reflectionDescContent is the schema descriptor for content field.
	reflectionDescContent := reflectionFields[2].Descriptor()
	// reflection.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	reflection.ContentValidator = reflectionDescContent.Validators[0].(func(string) error)
	// reflectionDescTokenCount is the schema descriptor for token_count field.
	reflectionDescTokenCount := reflectionFields[3].Descriptor()
	// reflection.DefaultTokenCount holds the default value on creation for the token_count field.
	reflection.DefaultTokenCount = reflectionDescTokenCount.Default.(int)
	// reflectionDescGeneration is the schema descriptor for generation field.
	reflectionDescGeneration := reflectionFields[4].Descriptor()
	// reflection.DefaultGeneration holds the default value on creation for the generation field.
	reflection.DefaultGeneration = reflectionDescGeneration.Default.(int)
	// reflectionDescCreatedAt is the schema descriptor for created_at field.
	reflectionDescCreatedAt := reflectionFields[5].Descriptor()
	// reflection.DefaultCreatedAt holds the default value on creation for the created_at field.
	reflection.DefaultCreatedAt = reflectionDescCreatedAt.Default.(func() time.Time)
	// reflectionDescID is the schema descriptor for id field.
	reflectionDescID := reflectionFields[0].Descriptor()
	// reflection.DefaultID holds the default value on creation for the id field.
	reflection.DefaultID = reflectionDescID.Default.(func() uuid.UUID)
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescName is the schema descriptor for name field.
	secretDescName := secretFields[1].Descriptor()
	// secret.NameValidator is a validator for the "name" field. It is called by the builders before save.
	secret.NameValidator = secretDescName.Validators[0].(func(string) error)
	// secretDescCreatedAt is the schema descriptor for created_at field.
	secretDescCreatedAt := secretFields[3].Descriptor()
	// secret.DefaultCreatedAt holds the default value on creation for the created_at field.
	secret.DefaultCreatedAt = secretDescCreatedAt.Default.(func() time.Time)
	// secretDescUpdatedAt is the schema descriptor for updated_at field.
	secretDescUpdatedAt := secretFields[4].Descriptor()
	// secret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	secret.DefaultUpdatedAt = secretDescUpdatedAt.Default.(func() time.Time)
	// secret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	secret.UpdateDefaultUpdatedAt = secretDescUpdatedAt.UpdateDefault.(func() time.Time)
	// secretDescAccessCount is the schema descriptor for access_count field.
	secretDescAccessCount := secretFields[5].Descriptor()
	// secret.DefaultAccessCount holds the default value on creation for the access_count field.
	secret.DefaultAccessCount = secretDescAccessCount.Default.(int)
	// secretDescID is the schema descriptor for id field.
	secretDescID := secretFields[0].Descriptor()
	// secret.DefaultID holds the default value on creation for the id field.
	secret.DefaultID = secretDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescKey is the schema descriptor for key field.
	sessionDescKey := sessionFields[0].Descriptor()
	// session.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	session.KeyValidator = sessionDescKey.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[6].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[7].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	workflowrunFields := schema.WorkflowRun{}.Fields()
	_ = workflowrunFields
	// workflowrunDescWorkflowName is the schema descriptor for workflow_name field.
	workflowrunDescWorkflowName := workflowrunFields[1].Descriptor()
	// workflowrun.WorkflowNameValidator is a validator for the "workflow_name" field. It is called by the builders before save.
	workflowrun.WorkflowNameValidator = workflowrunDescWorkflowName.Validators[0].(func(string) error)
	// workflowrunDescTotalSteps is the schema descriptor for total_steps field.
	workflowrunDescTotalSteps := workflowrunFields[4].Descriptor()
	// workflowrun.DefaultTotalSteps holds the default value on creation for the total_steps field.
	workflowrun.DefaultTotalSteps = workflowrunDescTotalSteps.Default.(int)
	// workflowrunDescCompletedSteps is the schema descriptor for completed_steps field.
	workflowrunDescCompletedSteps := workflowrunFields[5].Descriptor()
	// workflowrun.DefaultCompletedSteps holds the default value on creation for the completed_steps field.
	workflowrun.DefaultCompletedSteps = workflowrunDescCompletedSteps.Default.(int)
	// workflowrunDescStartedAt is the schema descriptor for started_at field.
	workflowrunDescStartedAt := workflowrunFields[7].Descriptor()
	// workflowrun.DefaultStartedAt holds the default value on creation for the started_at field.
	workflowrun.DefaultStartedAt = workflowrunDescStartedAt.Default.(func() time.Time)
	// workflowrunDescID is the schema descriptor for id field.
	workflowrunDescID := workflowrunFields[0].Descriptor()
	// workflowrun.DefaultID holds the default value on creation for the id field.
	workflowrun.DefaultID = workflowrunDescID.Default.(func() uuid.UUID)
	workflowsteprunFields := schema.WorkflowStepRun{}.Fields()
	_ = workflowsteprunFields
	// workflowsteprunDescStepID is the schema descriptor for step_id field.
	workflowsteprunDescStepID := workflowsteprunFields[2].Descriptor()
	// workflowsteprun.StepIDValidator is a validator for the "step_id" field. It is called by the builders before save.
	workflowsteprun.StepIDValidator = workflowsteprunDescStepID.Validators[0].(func(string) error)
	// workflowsteprunDescID is the schema descriptor for id field.
	workflowsteprunDescID := workflowsteprunFields[0].Descriptor()
	// workflowsteprun.DefaultID holds the default value on creation for the id field.
	workflowsteprun.DefaultID = workflowsteprunDescID.Default.(func() uuid.UUID)
}
