// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/workflowsteprun"
)

// WorkflowStepRun is the model entity for the WorkflowStepRun schema.
type WorkflowStepRun struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Reference to the parent WorkflowRun
	RunID uuid.UUID `json:"run_id,omitempty"`
	// Step identifier within the workflow YAML
	StepID string `json:"step_id,omitempty"`
	// Sub-agent that executed this step
	Agent string `json:"agent,omitempty"`
	// Rendered prompt (after template substitution)
	Prompt string `json:"prompt,omitempty"`
	// Status holds the value of the "status" field.
	Status workflowsteprun.Status `json:"status,omitempty"`
	// Step output/result
	Result string `json:"result,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowStepRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowsteprun.FieldStepID, workflowsteprun.FieldAgent, workflowsteprun.FieldPrompt, workflowsteprun.FieldStatus, workflowsteprun.FieldResult, workflowsteprun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case workflowsteprun.FieldStartedAt, workflowsteprun.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case workflowsteprun.FieldID, workflowsteprun.FieldRunID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowStepRun fields.
func (_m *WorkflowStepRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowsteprun.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case workflowsteprun.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				_m.RunID = *value
			}
		case workflowsteprun.FieldStepID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field step_id", values[i])
			} else if value.Valid {
				_m.StepID = value.String
			}
		case workflowsteprun.FieldAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent", values[i])
			} else if value.Valid {
				_m.Agent = value.String
			}
		case workflowsteprun.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case workflowsteprun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = workflowsteprun.Status(value.String)
			}
		case workflowsteprun.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case workflowsteprun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case workflowsteprun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case workflowsteprun.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowStepRun.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowStepRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowStepRun.
// Note that you need to call WorkflowStepRun.Unwrap() before calling this method if this WorkflowStepRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowStepRun) Update() *WorkflowStepRunUpdateOne {
	return NewWorkflowStepRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowStepRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowStepRun) Unwrap() *WorkflowStepRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowStepRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowStepRun) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowStepRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	builder.WriteString("step_id=")
	builder.WriteString(_m.StepID)
	builder.WriteString(", ")
	builder.WriteString("agent=")
	builder.WriteString(_m.Agent)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowStepRuns is a parsable slice of WorkflowStepRun.
type WorkflowStepRuns []*WorkflowStepRun
