// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langowarny/lango/internal/ent/predicate"
	"github.com/langowarny/lango/internal/ent/workflowrun"
)

// WorkflowRunUpdate is the builder for updating WorkflowRun entities.
type WorkflowRunUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdate) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkflowName sets the "workflow_name" field.
func (_u *WorkflowRunUpdate) SetWorkflowName(v string) *WorkflowRunUpdate {
	_u.mutation.SetWorkflowName(v)
	return _u
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableWorkflowName(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetWorkflowName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkflowRunUpdate) SetDescription(v string) *WorkflowRunUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableDescription(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorkflowRunUpdate) ClearDescription() *WorkflowRunUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdate) SetStatus(v workflowrun.Status) *WorkflowRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStatus(v *workflowrun.Status) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalSteps sets the "total_steps" field.
func (_u *WorkflowRunUpdate) SetTotalSteps(v int) *WorkflowRunUpdate {
	_u.mutation.ResetTotalSteps()
	_u.mutation.SetTotalSteps(v)
	return _u
}

// SetNillableTotalSteps sets the "total_steps" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableTotalSteps(v *int) *WorkflowRunUpdate {
	if v != nil {
		_u.SetTotalSteps(*v)
	}
	return _u
}

// AddTotalSteps adds value to the "total_steps" field.
func (_u *WorkflowRunUpdate) AddTotalSteps(v int) *WorkflowRunUpdate {
	_u.mutation.AddTotalSteps(v)
	return _u
}

// SetCompletedSteps sets the "completed_steps" field.
func (_u *WorkflowRunUpdate) SetCompletedSteps(v int) *WorkflowRunUpdate {
	_u.mutation.ResetCompletedSteps()
	_u.mutation.SetCompletedSteps(v)
	return _u
}

// SetNillableCompletedSteps sets the "completed_steps" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableCompletedSteps(v *int) *WorkflowRunUpdate {
	if v != nil {
		_u.SetCompletedSteps(*v)
	}
	return _u
}

// AddCompletedSteps adds value to the "completed_steps" field.
func (_u *WorkflowRunUpdate) AddCompletedSteps(v int) *WorkflowRunUpdate {
	_u.mutation.AddCompletedSteps(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WorkflowRunUpdate) SetErrorMessage(v string) *WorkflowRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableErrorMessage(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WorkflowRunUpdate) ClearErrorMessage() *WorkflowRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *WorkflowRunUpdate) SetCompletedAt(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableCompletedAt(v *time.Time) *WorkflowRunUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *WorkflowRunUpdate) ClearCompletedAt() *WorkflowRunUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdate) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdate) check() error {
	if v, ok := _u.mutation.WorkflowName(); ok {
		if err := workflowrun.WorkflowNameValidator(v); err != nil {
			return &ValidationError{Name: "workflow_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.workflow_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkflowName(); ok {
		_spec.SetField(workflowrun.FieldWorkflowName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workflowrun.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(workflowrun.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalSteps(); ok {
		_spec.SetField(workflowrun.FieldTotalSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSteps(); ok {
		_spec.AddField(workflowrun.FieldTotalSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedSteps(); ok {
		_spec.SetField(workflowrun.FieldCompletedSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedSteps(); ok {
		_spec.AddField(workflowrun.FieldCompletedSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflowrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(workflowrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(workflowrun.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowRunUpdateOne is the builder for updating a single WorkflowRun entity.
type WorkflowRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// SetWorkflowName sets the "workflow_name" field.
func (_u *WorkflowRunUpdateOne) SetWorkflowName(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetWorkflowName(v)
	return _u
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableWorkflowName(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetWorkflowName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkflowRunUpdateOne) SetDescription(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableDescription(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorkflowRunUpdateOne) ClearDescription() *WorkflowRunUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdateOne) SetStatus(v workflowrun.Status) *WorkflowRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStatus(v *workflowrun.Status) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalSteps sets the "total_steps" field.
func (_u *WorkflowRunUpdateOne) SetTotalSteps(v int) *WorkflowRunUpdateOne {
	_u.mutation.ResetTotalSteps()
	_u.mutation.SetTotalSteps(v)
	return _u
}

// SetNillableTotalSteps sets the "total_steps" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableTotalSteps(v *int) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetTotalSteps(*v)
	}
	return _u
}

// AddTotalSteps adds value to the "total_steps" field.
func (_u *WorkflowRunUpdateOne) AddTotalSteps(v int) *WorkflowRunUpdateOne {
	_u.mutation.AddTotalSteps(v)
	return _u
}

// SetCompletedSteps sets the "completed_steps" field.
func (_u *WorkflowRunUpdateOne) SetCompletedSteps(v int) *WorkflowRunUpdateOne {
	_u.mutation.ResetCompletedSteps()
	_u.mutation.SetCompletedSteps(v)
	return _u
}

// SetNillableCompletedSteps sets the "completed_steps" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableCompletedSteps(v *int) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetCompletedSteps(*v)
	}
	return _u
}

// AddCompletedSteps adds value to the "completed_steps" field.
func (_u *WorkflowRunUpdateOne) AddCompletedSteps(v int) *WorkflowRunUpdateOne {
	_u.mutation.AddCompletedSteps(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WorkflowRunUpdateOne) SetErrorMessage(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableErrorMessage(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WorkflowRunUpdateOne) ClearErrorMessage() *WorkflowRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *WorkflowRunUpdateOne) SetCompletedAt(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableCompletedAt(v *time.Time) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *WorkflowRunUpdateOne) ClearCompletedAt() *WorkflowRunUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdateOne) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdateOne) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowRunUpdateOne) Select(field string, fields ...string) *WorkflowRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowRun entity.
func (_u *WorkflowRunUpdateOne) Save(ctx context.Context) (*WorkflowRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) SaveX(ctx context.Context) *WorkflowRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdateOne) check() error {
	if v, ok := _u.mutation.WorkflowName(); ok {
		if err := workflowrun.WorkflowNameValidator(v); err != nil {
			return &ValidationError{Name: "workflow_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.workflow_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowRunUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowrun.FieldID)
		for _, f := range fields {
			if !workflowrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkflowName(); ok {
		_spec.SetField(workflowrun.FieldWorkflowName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workflowrun.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(workflowrun.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalSteps(); ok {
		_spec.SetField(workflowrun.FieldTotalSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSteps(); ok {
		_spec.AddField(workflowrun.FieldTotalSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedSteps(); ok {
		_spec.SetField(workflowrun.FieldCompletedSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedSteps(); ok {
		_spec.AddField(workflowrun.FieldCompletedSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflowrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(workflowrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(workflowrun.FieldCompletedAt, field.TypeTime)
	}
	_node = &WorkflowRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
