// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/workflowrun"
)

// WorkflowRunCreate is the builder for creating a WorkflowRun entity.
type WorkflowRunCreate struct {
	config
	mutation *WorkflowRunMutation
	hooks    []Hook
}

// SetWorkflowName sets the "workflow_name" field.
func (_c *WorkflowRunCreate) SetWorkflowName(v string) *WorkflowRunCreate {
	_c.mutation.SetWorkflowName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *WorkflowRunCreate) SetDescription(v string) *WorkflowRunCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableDescription(v *string) *WorkflowRunCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkflowRunCreate) SetStatus(v workflowrun.Status) *WorkflowRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableStatus(v *workflowrun.Status) *WorkflowRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalSteps sets the "total_steps" field.
func (_c *WorkflowRunCreate) SetTotalSteps(v int) *WorkflowRunCreate {
	_c.mutation.SetTotalSteps(v)
	return _c
}

// SetNillableTotalSteps sets the "total_steps" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableTotalSteps(v *int) *WorkflowRunCreate {
	if v != nil {
		_c.SetTotalSteps(*v)
	}
	return _c
}

// SetCompletedSteps sets the "completed_steps" field.
func (_c *WorkflowRunCreate) SetCompletedSteps(v int) *WorkflowRunCreate {
	_c.mutation.SetCompletedSteps(v)
	return _c
}

// SetNillableCompletedSteps sets the "completed_steps" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableCompletedSteps(v *int) *WorkflowRunCreate {
	if v != nil {
		_c.SetCompletedSteps(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *WorkflowRunCreate) SetErrorMessage(v string) *WorkflowRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableErrorMessage(v *string) *WorkflowRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *WorkflowRunCreate) SetStartedAt(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableStartedAt(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *WorkflowRunCreate) SetCompletedAt(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableCompletedAt(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkflowRunCreate) SetID(v uuid.UUID) *WorkflowRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableID(v *uuid.UUID) *WorkflowRunCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_c *WorkflowRunCreate) Mutation() *WorkflowRunMutation {
	return _c.mutation
}

// Save creates the WorkflowRun in the database.
func (_c *WorkflowRunCreate) Save(ctx context.Context) (*WorkflowRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkflowRunCreate) SaveX(ctx context.Context) *WorkflowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkflowRunCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := workflowrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalSteps(); !ok {
		v := workflowrun.DefaultTotalSteps
		_c.mutation.SetTotalSteps(v)
	}
	if _, ok := _c.mutation.CompletedSteps(); !ok {
		v := workflowrun.DefaultCompletedSteps
		_c.mutation.SetCompletedSteps(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := workflowrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := workflowrun.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkflowRunCreate) check() error {
	if _, ok := _c.mutation.WorkflowName(); !ok {
		return &ValidationError{Name: "workflow_name", err: errors.New(`ent: missing required field "WorkflowRun.workflow_name"`)}
	}
	if v, ok := _c.mutation.WorkflowName(); ok {
		if err := workflowrun.WorkflowNameValidator(v); err != nil {
			return &ValidationError{Name: "workflow_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.workflow_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkflowRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalSteps(); !ok {
		return &ValidationError{Name: "total_steps", err: errors.New(`ent: missing required field "WorkflowRun.total_steps"`)}
	}
	if _, ok := _c.mutation.CompletedSteps(); !ok {
		return &ValidationError{Name: "completed_steps", err: errors.New(`ent: missing required field "WorkflowRun.completed_steps"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "WorkflowRun.started_at"`)}
	}
	return nil
}

func (_c *WorkflowRunCreate) sqlSave(ctx context.Context) (*WorkflowRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkflowRunCreate) createSpec() (*WorkflowRun, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workflowrun.Table, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.WorkflowName(); ok {
		_spec.SetField(workflowrun.FieldWorkflowName, field.TypeString, value)
		_node.WorkflowName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(workflowrun.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalSteps(); ok {
		_spec.SetField(workflowrun.FieldTotalSteps, field.TypeInt, value)
		_node.TotalSteps = value
	}
	if value, ok := _c.mutation.CompletedSteps(); ok {
		_spec.SetField(workflowrun.FieldCompletedSteps, field.TypeInt, value)
		_node.CompletedSteps = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(workflowrun.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// WorkflowRunCreateBulk is the builder for creating many WorkflowRun entities in bulk.
type WorkflowRunCreateBulk struct {
	config
	err      error
	builders []*WorkflowRunCreate
}

// Save creates the WorkflowRun entities in the database.
func (_c *WorkflowRunCreateBulk) Save(ctx context.Context) ([]*WorkflowRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkflowRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkflowRunCreateBulk) SaveX(ctx context.Context) []*WorkflowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
