// Code generated by ent, DO NOT EDIT.

package paymenttx

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldID, id))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldTxHash, v))
}

// FromAddress applies equality check predicate on the "from_address" field. It's identical to FromAddressEQ.
func FromAddress(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldFromAddress, v))
}

// ToAddress applies equality check predicate on the "to_address" field. It's identical to ToAddressEQ.
func ToAddress(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldToAddress, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldAmount, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldChainID, v))
}

// SessionKey applies equality check predicate on the "session_key" field. It's identical to SessionKeyEQ.
func SessionKey(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldSessionKey, v))
}

// Purpose applies equality check predicate on the "purpose" field. It's identical to PurposeEQ.
func Purpose(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldPurpose, v))
}

// X402URL applies equality check predicate on the "x402_url" field. It's identical to X402URLEQ.
func X402URL(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldX402URL, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldUpdatedAt, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashIsNil applies the IsNil predicate on the "tx_hash" field.
func TxHashIsNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIsNull(FieldTxHash))
}

// TxHashNotNil applies the NotNil predicate on the "tx_hash" field.
func TxHashNotNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotNull(FieldTxHash))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldTxHash, v))
}

// FromAddressEQ applies the EQ predicate on the "from_address" field.
func FromAddressEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldFromAddress, v))
}

// FromAddressNEQ applies the NEQ predicate on the "from_address" field.
func FromAddressNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldFromAddress, v))
}

// FromAddressIn applies the In predicate on the "from_address" field.
func FromAddressIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldFromAddress, vs...))
}

// FromAddressNotIn applies the NotIn predicate on the "from_address" field.
func FromAddressNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldFromAddress, vs...))
}

// FromAddressGT applies the GT predicate on the "from_address" field.
func FromAddressGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldFromAddress, v))
}

// FromAddressGTE applies the GTE predicate on the "from_address" field.
func FromAddressGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldFromAddress, v))
}

// FromAddressLT applies the LT predicate on the "from_address" field.
func FromAddressLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldFromAddress, v))
}

// FromAddressLTE applies the LTE predicate on the "from_address" field.
func FromAddressLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldFromAddress, v))
}

// FromAddressContains applies the Contains predicate on the "from_address" field.
func FromAddressContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldFromAddress, v))
}

// FromAddressHasPrefix applies the HasPrefix predicate on the "from_address" field.
func FromAddressHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldFromAddress, v))
}

// FromAddressHasSuffix applies the HasSuffix predicate on the "from_address" field.
func FromAddressHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldFromAddress, v))
}

// FromAddressEqualFold applies the EqualFold predicate on the "from_address" field.
func FromAddressEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldFromAddress, v))
}

// FromAddressContainsFold applies the ContainsFold predicate on the "from_address" field.
func FromAddressContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldFromAddress, v))
}

// ToAddressEQ applies the EQ predicate on the "to_address" field.
func ToAddressEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldToAddress, v))
}

// ToAddressNEQ applies the NEQ predicate on the "to_address" field.
func ToAddressNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldToAddress, v))
}

// ToAddressIn applies the In predicate on the "to_address" field.
func ToAddressIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldToAddress, vs...))
}

// ToAddressNotIn applies the NotIn predicate on the "to_address" field.
func ToAddressNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldToAddress, vs...))
}

// ToAddressGT applies the GT predicate on the "to_address" field.
func ToAddressGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldToAddress, v))
}

// ToAddressGTE applies the GTE predicate on the "to_address" field.
func ToAddressGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldToAddress, v))
}

// ToAddressLT applies the LT predicate on the "to_address" field.
func ToAddressLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldToAddress, v))
}

// ToAddressLTE applies the LTE predicate on the "to_address" field.
func ToAddressLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldToAddress, v))
}

// ToAddressContains applies the Contains predicate on the "to_address" field.
func ToAddressContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldToAddress, v))
}

// ToAddressHasPrefix applies the HasPrefix predicate on the "to_address" field.
func ToAddressHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldToAddress, v))
}

// ToAddressHasSuffix applies the HasSuffix predicate on the "to_address" field.
func ToAddressHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldToAddress, v))
}

// ToAddressEqualFold applies the EqualFold predicate on the "to_address" field.
func ToAddressEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldToAddress, v))
}

// ToAddressContainsFold applies the ContainsFold predicate on the "to_address" field.
func ToAddressContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldToAddress, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldAmount, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int64) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldChainID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldStatus, vs...))
}

// SessionKeyEQ applies the EQ predicate on the "session_key" field.
func SessionKeyEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldSessionKey, v))
}

// SessionKeyNEQ applies the NEQ predicate on the "session_key" field.
func SessionKeyNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldSessionKey, v))
}

// SessionKeyIn applies the In predicate on the "session_key" field.
func SessionKeyIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldSessionKey, vs...))
}

// SessionKeyNotIn applies the NotIn predicate on the "session_key" field.
func SessionKeyNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldSessionKey, vs...))
}

// SessionKeyGT applies the GT predicate on the "session_key" field.
func SessionKeyGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldSessionKey, v))
}

// SessionKeyGTE applies the GTE predicate on the "session_key" field.
func SessionKeyGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldSessionKey, v))
}

// SessionKeyLT applies the LT predicate on the "session_key" field.
func SessionKeyLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldSessionKey, v))
}

// SessionKeyLTE applies the LTE predicate on the "session_key" field.
func SessionKeyLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldSessionKey, v))
}

// SessionKeyContains applies the Contains predicate on the "session_key" field.
func SessionKeyContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldSessionKey, v))
}

// SessionKeyHasPrefix applies the HasPrefix predicate on the "session_key" field.
func SessionKeyHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldSessionKey, v))
}

// SessionKeyHasSuffix applies the HasSuffix predicate on the "session_key" field.
func SessionKeyHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldSessionKey, v))
}

// SessionKeyIsNil applies the IsNil predicate on the "session_key" field.
func SessionKeyIsNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIsNull(FieldSessionKey))
}

// SessionKeyNotNil applies the NotNil predicate on the "session_key" field.
func SessionKeyNotNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotNull(FieldSessionKey))
}

// SessionKeyEqualFold applies the EqualFold predicate on the "session_key" field.
func SessionKeyEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldSessionKey, v))
}

// SessionKeyContainsFold applies the ContainsFold predicate on the "session_key" field.
func SessionKeyContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldSessionKey, v))
}

// PurposeEQ applies the EQ predicate on the "purpose" field.
func PurposeEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldPurpose, v))
}

// PurposeNEQ applies the NEQ predicate on the "purpose" field.
func PurposeNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldPurpose, v))
}

// PurposeIn applies the In predicate on the "purpose" field.
func PurposeIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldPurpose, vs...))
}

// PurposeNotIn applies the NotIn predicate on the "purpose" field.
func PurposeNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldPurpose, vs...))
}

// PurposeGT applies the GT predicate on the "purpose" field.
func PurposeGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldPurpose, v))
}

// PurposeGTE applies the GTE predicate on the "purpose" field.
func PurposeGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldPurpose, v))
}

// PurposeLT applies the LT predicate on the "purpose" field.
func PurposeLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldPurpose, v))
}

// PurposeLTE applies the LTE predicate on the "purpose" field.
func PurposeLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldPurpose, v))
}

// PurposeContains applies the Contains predicate on the "purpose" field.
func PurposeContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldPurpose, v))
}

// PurposeHasPrefix applies the HasPrefix predicate on the "purpose" field.
func PurposeHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldPurpose, v))
}

// PurposeHasSuffix applies the HasSuffix predicate on the "purpose" field.
func PurposeHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldPurpose, v))
}

// PurposeIsNil applies the IsNil predicate on the "purpose" field.
func PurposeIsNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIsNull(FieldPurpose))
}

// PurposeNotNil applies the NotNil predicate on the "purpose" field.
func PurposeNotNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotNull(FieldPurpose))
}

// PurposeEqualFold applies the EqualFold predicate on the "purpose" field.
func PurposeEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldPurpose, v))
}

// PurposeContainsFold applies the ContainsFold predicate on the "purpose" field.
func PurposeContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldPurpose, v))
}

// X402URLEQ applies the EQ predicate on the "x402_url" field.
func X402URLEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldX402URL, v))
}

// X402URLNEQ applies the NEQ predicate on the "x402_url" field.
func X402URLNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldX402URL, v))
}

// X402URLIn applies the In predicate on the "x402_url" field.
func X402URLIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldX402URL, vs...))
}

// X402URLNotIn applies the NotIn predicate on the "x402_url" field.
func X402URLNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldX402URL, vs...))
}

// X402URLGT applies the GT predicate on the "x402_url" field.
func X402URLGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldX402URL, v))
}

// X402URLGTE applies the GTE predicate on the "x402_url" field.
func X402URLGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldX402URL, v))
}

// X402URLLT applies the LT predicate on the "x402_url" field.
func X402URLLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldX402URL, v))
}

// X402URLLTE applies the LTE predicate on the "x402_url" field.
func X402URLLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldX402URL, v))
}

// X402URLContains applies the Contains predicate on the "x402_url" field.
func X402URLContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldX402URL, v))
}

// X402URLHasPrefix applies the HasPrefix predicate on the "x402_url" field.
func X402URLHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldX402URL, v))
}

// X402URLHasSuffix applies the HasSuffix predicate on the "x402_url" field.
func X402URLHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldX402URL, v))
}

// X402URLIsNil applies the IsNil predicate on the "x402_url" field.
func X402URLIsNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIsNull(FieldX402URL))
}

// X402URLNotNil applies the NotNil predicate on the "x402_url" field.
func X402URLNotNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotNull(FieldX402URL))
}

// X402URLEqualFold applies the EqualFold predicate on the "x402_url" field.
func X402URLEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldX402URL, v))
}

// X402URLContainsFold applies the ContainsFold predicate on the "x402_url" field.
func X402URLContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldX402URL, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentTx {
	return predicate.PaymentTx(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentTx) predicate.PaymentTx {
	return predicate.PaymentTx(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentTx) predicate.PaymentTx {
	return predicate.PaymentTx(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentTx) predicate.PaymentTx {
	return predicate.PaymentTx(sql.NotPredicates(p))
}
