// Code generated by ent, DO NOT EDIT.

package cronjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldName, v))
}

// Schedule applies equality check predicate on the "schedule" field. It's identical to ScheduleEQ.
func Schedule(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldSchedule, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldPrompt, v))
}

// SessionMode applies equality check predicate on the "session_mode" field. It's identical to SessionModeEQ.
func SessionMode(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldSessionMode, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldTimezone, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldEnabled, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldLastRunAt, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldNextRunAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContainsFold(FieldName, v))
}

// ScheduleTypeEQ applies the EQ predicate on the "schedule_type" field.
func ScheduleTypeEQ(v ScheduleType) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldScheduleType, v))
}

// ScheduleTypeNEQ applies the NEQ predicate on the "schedule_type" field.
func ScheduleTypeNEQ(v ScheduleType) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldScheduleType, v))
}

// ScheduleTypeIn applies the In predicate on the "schedule_type" field.
func ScheduleTypeIn(vs ...ScheduleType) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldScheduleType, vs...))
}

// ScheduleTypeNotIn applies the NotIn predicate on the "schedule_type" field.
func ScheduleTypeNotIn(vs ...ScheduleType) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldScheduleType, vs...))
}

// ScheduleEQ applies the EQ predicate on the "schedule" field.
func ScheduleEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldSchedule, v))
}

// ScheduleNEQ applies the NEQ predicate on the "schedule" field.
func ScheduleNEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldSchedule, v))
}

// ScheduleIn applies the In predicate on the "schedule" field.
func ScheduleIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldSchedule, vs...))
}

// ScheduleNotIn applies the NotIn predicate on the "schedule" field.
func ScheduleNotIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldSchedule, vs...))
}

// ScheduleGT applies the GT predicate on the "schedule" field.
func ScheduleGT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldSchedule, v))
}

// ScheduleGTE applies the GTE predicate on the "schedule" field.
func ScheduleGTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldSchedule, v))
}

// ScheduleLT applies the LT predicate on the "schedule" field.
func ScheduleLT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldSchedule, v))
}

// ScheduleLTE applies the LTE predicate on the "schedule" field.
func ScheduleLTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldSchedule, v))
}

// ScheduleContains applies the Contains predicate on the "schedule" field.
func ScheduleContains(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContains(FieldSchedule, v))
}

// ScheduleHasPrefix applies the HasPrefix predicate on the "schedule" field.
func ScheduleHasPrefix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasPrefix(FieldSchedule, v))
}

// ScheduleHasSuffix applies the HasSuffix predicate on the "schedule" field.
func ScheduleHasSuffix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasSuffix(FieldSchedule, v))
}

// ScheduleEqualFold applies the EqualFold predicate on the "schedule" field.
func ScheduleEqualFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEqualFold(FieldSchedule, v))
}

// ScheduleContainsFold applies the ContainsFold predicate on the "schedule" field.
func ScheduleContainsFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContainsFold(FieldSchedule, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContainsFold(FieldPrompt, v))
}

// SessionModeEQ applies the EQ predicate on the "session_mode" field.
func SessionModeEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldSessionMode, v))
}

// SessionModeNEQ applies the NEQ predicate on the "session_mode" field.
func SessionModeNEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldSessionMode, v))
}

// SessionModeIn applies the In predicate on the "session_mode" field.
func SessionModeIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldSessionMode, vs...))
}

// SessionModeNotIn applies the NotIn predicate on the "session_mode" field.
func SessionModeNotIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldSessionMode, vs...))
}

// SessionModeGT applies the GT predicate on the "session_mode" field.
func SessionModeGT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldSessionMode, v))
}

// SessionModeGTE applies the GTE predicate on the "session_mode" field.
func SessionModeGTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldSessionMode, v))
}

// SessionModeLT applies the LT predicate on the "session_mode" field.
func SessionModeLT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldSessionMode, v))
}

// SessionModeLTE applies the LTE predicate on the "session_mode" field.
func SessionModeLTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldSessionMode, v))
}

// SessionModeContains applies the Contains predicate on the "session_mode" field.
func SessionModeContains(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContains(FieldSessionMode, v))
}

// SessionModeHasPrefix applies the HasPrefix predicate on the "session_mode" field.
func SessionModeHasPrefix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasPrefix(FieldSessionMode, v))
}

// SessionModeHasSuffix applies the HasSuffix predicate on the "session_mode" field.
func SessionModeHasSuffix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasSuffix(FieldSessionMode, v))
}

// SessionModeEqualFold applies the EqualFold predicate on the "session_mode" field.
func SessionModeEqualFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEqualFold(FieldSessionMode, v))
}

// SessionModeContainsFold applies the ContainsFold predicate on the "session_mode" field.
func SessionModeContainsFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContainsFold(FieldSessionMode, v))
}

// DeliverToIsNil applies the IsNil predicate on the "deliver_to" field.
func DeliverToIsNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldIsNull(FieldDeliverTo))
}

// DeliverToNotNil applies the NotNil predicate on the "deliver_to" field.
func DeliverToNotNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldNotNull(FieldDeliverTo))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.CronJob {
	return predicate.CronJob(sql.FieldContainsFold(FieldTimezone, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldEnabled, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldNotNull(FieldLastRunAt))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldNextRunAt, v))
}

// NextRunAtIsNil applies the IsNil predicate on the "next_run_at" field.
func NextRunAtIsNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldIsNull(FieldNextRunAt))
}

// NextRunAtNotNil applies the NotNil predicate on the "next_run_at" field.
func NextRunAtNotNil() predicate.CronJob {
	return predicate.CronJob(sql.FieldNotNull(FieldNextRunAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CronJob {
	return predicate.CronJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CronJob) predicate.CronJob {
	return predicate.CronJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CronJob) predicate.CronJob {
	return predicate.CronJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CronJob) predicate.CronJob {
	return predicate.CronJob(sql.NotPredicates(p))
}
