// Code generated by ent, DO NOT EDIT.

package cronjobhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langowarny/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldJobID, v))
}

// JobName applies equality check predicate on the "job_name" field. It's identical to JobNameEQ.
func JobName(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldJobName, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldPrompt, v))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldResult, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldErrorMessage, v))
}

// TokensUsed applies equality check predicate on the "tokens_used" field. It's identical to TokensUsedEQ.
func TokensUsed(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldTokensUsed, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldCompletedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v uuid.UUID) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldJobID, v))
}

// JobNameEQ applies the EQ predicate on the "job_name" field.
func JobNameEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldJobName, v))
}

// JobNameNEQ applies the NEQ predicate on the "job_name" field.
func JobNameNEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldJobName, v))
}

// JobNameIn applies the In predicate on the "job_name" field.
func JobNameIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldJobName, vs...))
}

// JobNameNotIn applies the NotIn predicate on the "job_name" field.
func JobNameNotIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldJobName, vs...))
}

// JobNameGT applies the GT predicate on the "job_name" field.
func JobNameGT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldJobName, v))
}

// JobNameGTE applies the GTE predicate on the "job_name" field.
func JobNameGTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldJobName, v))
}

// JobNameLT applies the LT predicate on the "job_name" field.
func JobNameLT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldJobName, v))
}

// JobNameLTE applies the LTE predicate on the "job_name" field.
func JobNameLTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldJobName, v))
}

// JobNameContains applies the Contains predicate on the "job_name" field.
func JobNameContains(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContains(FieldJobName, v))
}

// JobNameHasPrefix applies the HasPrefix predicate on the "job_name" field.
func JobNameHasPrefix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasPrefix(FieldJobName, v))
}

// JobNameHasSuffix applies the HasSuffix predicate on the "job_name" field.
func JobNameHasSuffix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasSuffix(FieldJobName, v))
}

// JobNameEqualFold applies the EqualFold predicate on the "job_name" field.
func JobNameEqualFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEqualFold(FieldJobName, v))
}

// JobNameContainsFold applies the ContainsFold predicate on the "job_name" field.
func JobNameContainsFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContainsFold(FieldJobName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldStatus, vs...))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContainsFold(FieldPrompt, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldResult, vs...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldResult, v))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldResult, v))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldResult, v))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldResult, v))
}

// ResultContains applies the Contains predicate on the "result" field.
func ResultContains(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContains(FieldResult, v))
}

// ResultHasPrefix applies the HasPrefix predicate on the "result" field.
func ResultHasPrefix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasPrefix(FieldResult, v))
}

// ResultHasSuffix applies the HasSuffix predicate on the "result" field.
func ResultHasSuffix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasSuffix(FieldResult, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotNull(FieldResult))
}

// ResultEqualFold applies the EqualFold predicate on the "result" field.
func ResultEqualFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEqualFold(FieldResult, v))
}

// ResultContainsFold applies the ContainsFold predicate on the "result" field.
func ResultContainsFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContainsFold(FieldResult, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldContainsFold(FieldErrorMessage, v))
}

// TokensUsedEQ applies the EQ predicate on the "tokens_used" field.
func TokensUsedEQ(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldTokensUsed, v))
}

// TokensUsedNEQ applies the NEQ predicate on the "tokens_used" field.
func TokensUsedNEQ(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldTokensUsed, v))
}

// TokensUsedIn applies the In predicate on the "tokens_used" field.
func TokensUsedIn(vs ...int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldTokensUsed, vs...))
}

// TokensUsedNotIn applies the NotIn predicate on the "tokens_used" field.
func TokensUsedNotIn(vs ...int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldTokensUsed, vs...))
}

// TokensUsedGT applies the GT predicate on the "tokens_used" field.
func TokensUsedGT(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldTokensUsed, v))
}

// TokensUsedGTE applies the GTE predicate on the "tokens_used" field.
func TokensUsedGTE(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldTokensUsed, v))
}

// TokensUsedLT applies the LT predicate on the "tokens_used" field.
func TokensUsedLT(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldTokensUsed, v))
}

// TokensUsedLTE applies the LTE predicate on the "tokens_used" field.
func TokensUsedLTE(v int) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldTokensUsed, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CronJobHistory) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CronJobHistory) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CronJobHistory) predicate.CronJobHistory {
	return predicate.CronJobHistory(sql.NotPredicates(p))
}
